// Code generated by hertz generator.

package token

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	base "kcers/idl_gen/model/base"
	token "kcers/idl_gen/model/token"
)

// UpdateToken .
// @router /api/admin/token/update [POST]
func UpdateToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req token.TokenInfo
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteToken .
// @router /api/admin/token [POST]
func DeleteToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req base.IdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}

// TokenList .
// @router /api/admin/token/list [POST]
func TokenList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req token.TokenListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}
