// Code generated by hertz generator.

package payment

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	base "kcers/idl_gen/model/base"
	payment "kcers/idl_gen/model/payment"
)

// WXPay .
// @router /service/payment/WXPay [POST]
func WXPay(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.PayReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}

// WXQRPay .
// @router /service/payment/WXQRPay [POST]
func WXQRPay(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.PayReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}

// WXRefundOrder .
// @router /service/payment/WXRefundOrder [POST]
func WXRefundOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.RefundOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}
