// Code generated by hertz generator.

package venue

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _placeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createplaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _placelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _placeupdatestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateplaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _venueMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}
