// Code generated by hertz generator.

package payment

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _serviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wxpayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wxqrpayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wxrefundorderMw() []app.HandlerFunc {
	// your code...
	return nil
}
