Name: Kcersing Admin
IsProd: true
Host: 0.0.0.0
Port: 9039
Timeout: 30000
Domain: http://127.0.0.1:9039/

Captcha:
  KeyLong: 5
  ImgWidth: 240
  ImgHeight: 80

Auth:
  OAuthKey: OauthJf3z1n2xxx2cr1
  AccessSecret: D86VKDtsJf3z1nxxxxtsJf3z1n5
  AccessExpire: 259200 # seconds, 3 days

Redis:
  Host: r-2ze5p4rpj6b4iikdo2.redis.rds.aliyuncs.com:6379
  Password: hIUc7JZguHSK4BtT1qDq

MySQL:
  #  Host: root:X3MeAGAmPSZp8A3H@tcp(121.40.98.240:3306)/kcers?parseTime=True
  Host: root:root@tcp(127.0.0.1:3306)/kcers?parseTime=True
  Salt: YOUR_SALT

PostgreSQL:
  Host: postgresql://postgres:root@127.0.0.1/postgres
  Salt: YOUR_SALT

Casbin:
  ModelText: |
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _, _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = r.sub == p.sub && keyMatch2(r.obj,p.obj) && r.act == p.act


Payment:
  Alipay:
    appid:
    private_key:
    app_public_cert_content:
    alipay_root_cert_content:
    alipay_public_cert_content:
  Wechat:
    appid:
    mch_id:
    api_key:
    api_v3_key:
    cert_file_content:
    key_file_content:
    pkcs12_file_content:
    serial_no:
    notify_url:

Minio:
  EndPoint : localhost:9000
  AccessKeyID : douyin
  SecretAccessKey : douyin123
  UseSSL : false
  VideoBucketName : videobucket
  ImgBucketName : imagebucket
  Url : http://localhost:9000

Aliyun:
  Access:
    AccessKeyId:
    AccessKeySecret:
  Sms:
    Captcha:
      SignName:
      TemplateCode :

DouYin:
  AppId :
  AppSecret :
  AccountId :