// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kcers/biz/dal/db/mysql/ent/member"
	"kcers/biz/dal/db/mysql/ent/memberdetails"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MemberDetails is the model entity for the MemberDetails schema.
type MemberDetails struct {
	config `json:"-"`
	// ID of the ent.
	// primary key
	ID int64 `json:"id,omitempty"`
	// created time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// last update time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// last delete  1:已删除
	Delete int64 `json:"delete,omitempty"`
	// created
	CreatedID int64 `json:"created_id,omitempty"`
	// 会员id
	MemberID int64 `json:"member_id,omitempty"`
	// 消费总金额
	MoneySum float64 `json:"money_sum,omitempty"`
	// 首次的产品
	ProductID int64 `json:"product_id,omitempty"`
	// 首次的产品
	ProductName string `json:"product_name,omitempty"`
	// 进馆总次数
	EntrySum int64 `json:"entry_sum,omitempty"`
	// 最后一次进馆时间
	EntryLastAt time.Time `json:"entry_last_at,omitempty"`
	// 进馆最后期限时间
	EntryDeadlineAt time.Time `json:"entry_deadline_at,omitempty"`
	// 最后一次上课时间
	ClassLastAt time.Time `json:"class_last_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemberDetailsQuery when eager-loading is set.
	Edges        MemberDetailsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MemberDetailsEdges holds the relations/edges for other nodes in the graph.
type MemberDetailsEdges struct {
	// Member holds the value of the member edge.
	Member *Member `json:"member,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MemberOrErr returns the Member value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemberDetailsEdges) MemberOrErr() (*Member, error) {
	if e.Member != nil {
		return e.Member, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: member.Label}
	}
	return nil, &NotLoadedError{edge: "member"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberDetails) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memberdetails.FieldMoneySum:
			values[i] = new(sql.NullFloat64)
		case memberdetails.FieldID, memberdetails.FieldDelete, memberdetails.FieldCreatedID, memberdetails.FieldMemberID, memberdetails.FieldProductID, memberdetails.FieldEntrySum:
			values[i] = new(sql.NullInt64)
		case memberdetails.FieldProductName:
			values[i] = new(sql.NullString)
		case memberdetails.FieldCreatedAt, memberdetails.FieldUpdatedAt, memberdetails.FieldEntryLastAt, memberdetails.FieldEntryDeadlineAt, memberdetails.FieldClassLastAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberDetails fields.
func (md *MemberDetails) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memberdetails.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			md.ID = int64(value.Int64)
		case memberdetails.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				md.CreatedAt = value.Time
			}
		case memberdetails.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				md.UpdatedAt = value.Time
			}
		case memberdetails.FieldDelete:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delete", values[i])
			} else if value.Valid {
				md.Delete = value.Int64
			}
		case memberdetails.FieldCreatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_id", values[i])
			} else if value.Valid {
				md.CreatedID = value.Int64
			}
		case memberdetails.FieldMemberID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value.Valid {
				md.MemberID = value.Int64
			}
		case memberdetails.FieldMoneySum:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field money_sum", values[i])
			} else if value.Valid {
				md.MoneySum = value.Float64
			}
		case memberdetails.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				md.ProductID = value.Int64
			}
		case memberdetails.FieldProductName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_name", values[i])
			} else if value.Valid {
				md.ProductName = value.String
			}
		case memberdetails.FieldEntrySum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entry_sum", values[i])
			} else if value.Valid {
				md.EntrySum = value.Int64
			}
		case memberdetails.FieldEntryLastAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field entry_last_at", values[i])
			} else if value.Valid {
				md.EntryLastAt = value.Time
			}
		case memberdetails.FieldEntryDeadlineAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field entry_deadline_at", values[i])
			} else if value.Valid {
				md.EntryDeadlineAt = value.Time
			}
		case memberdetails.FieldClassLastAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field class_last_at", values[i])
			} else if value.Valid {
				md.ClassLastAt = value.Time
			}
		default:
			md.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberDetails.
// This includes values selected through modifiers, order, etc.
func (md *MemberDetails) Value(name string) (ent.Value, error) {
	return md.selectValues.Get(name)
}

// QueryMember queries the "member" edge of the MemberDetails entity.
func (md *MemberDetails) QueryMember() *MemberQuery {
	return NewMemberDetailsClient(md.config).QueryMember(md)
}

// Update returns a builder for updating this MemberDetails.
// Note that you need to call MemberDetails.Unwrap() before calling this method if this MemberDetails
// was returned from a transaction, and the transaction was committed or rolled back.
func (md *MemberDetails) Update() *MemberDetailsUpdateOne {
	return NewMemberDetailsClient(md.config).UpdateOne(md)
}

// Unwrap unwraps the MemberDetails entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (md *MemberDetails) Unwrap() *MemberDetails {
	_tx, ok := md.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberDetails is not a transactional entity")
	}
	md.config.driver = _tx.drv
	return md
}

// String implements the fmt.Stringer.
func (md *MemberDetails) String() string {
	var builder strings.Builder
	builder.WriteString("MemberDetails(")
	builder.WriteString(fmt.Sprintf("id=%v, ", md.ID))
	builder.WriteString("created_at=")
	builder.WriteString(md.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(md.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("delete=")
	builder.WriteString(fmt.Sprintf("%v", md.Delete))
	builder.WriteString(", ")
	builder.WriteString("created_id=")
	builder.WriteString(fmt.Sprintf("%v", md.CreatedID))
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(fmt.Sprintf("%v", md.MemberID))
	builder.WriteString(", ")
	builder.WriteString("money_sum=")
	builder.WriteString(fmt.Sprintf("%v", md.MoneySum))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", md.ProductID))
	builder.WriteString(", ")
	builder.WriteString("product_name=")
	builder.WriteString(md.ProductName)
	builder.WriteString(", ")
	builder.WriteString("entry_sum=")
	builder.WriteString(fmt.Sprintf("%v", md.EntrySum))
	builder.WriteString(", ")
	builder.WriteString("entry_last_at=")
	builder.WriteString(md.EntryLastAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entry_deadline_at=")
	builder.WriteString(md.EntryDeadlineAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("class_last_at=")
	builder.WriteString(md.ClassLastAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MemberDetailsSlice is a parsable slice of MemberDetails.
type MemberDetailsSlice []*MemberDetails
