// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kcers/biz/dal/db/mysql/ent/api"
	"kcers/biz/dal/db/mysql/ent/banner"
	"kcers/biz/dal/db/mysql/ent/contract"
	"kcers/biz/dal/db/mysql/ent/dictionary"
	"kcers/biz/dal/db/mysql/ent/dictionarydetail"
	"kcers/biz/dal/db/mysql/ent/entrylogs"
	"kcers/biz/dal/db/mysql/ent/face"
	"kcers/biz/dal/db/mysql/ent/logs"
	"kcers/biz/dal/db/mysql/ent/member"
	"kcers/biz/dal/db/mysql/ent/membercontract"
	"kcers/biz/dal/db/mysql/ent/membercontractcontent"
	"kcers/biz/dal/db/mysql/ent/memberdetails"
	"kcers/biz/dal/db/mysql/ent/membernote"
	"kcers/biz/dal/db/mysql/ent/memberproduct"
	"kcers/biz/dal/db/mysql/ent/memberproductproperty"
	"kcers/biz/dal/db/mysql/ent/memberprofile"
	"kcers/biz/dal/db/mysql/ent/membertoken"
	"kcers/biz/dal/db/mysql/ent/menu"
	"kcers/biz/dal/db/mysql/ent/menuparam"
	"kcers/biz/dal/db/mysql/ent/messages"
	entorder "kcers/biz/dal/db/mysql/ent/order"
	"kcers/biz/dal/db/mysql/ent/orderamount"
	"kcers/biz/dal/db/mysql/ent/orderitem"
	"kcers/biz/dal/db/mysql/ent/orderpay"
	"kcers/biz/dal/db/mysql/ent/ordersales"
	"kcers/biz/dal/db/mysql/ent/product"
	"kcers/biz/dal/db/mysql/ent/productproperty"
	"kcers/biz/dal/db/mysql/ent/role"
	"kcers/biz/dal/db/mysql/ent/schedule"
	"kcers/biz/dal/db/mysql/ent/schedulecoach"
	"kcers/biz/dal/db/mysql/ent/schedulemember"
	"kcers/biz/dal/db/mysql/ent/schema"
	"kcers/biz/dal/db/mysql/ent/sms"
	"kcers/biz/dal/db/mysql/ent/smslog"
	"kcers/biz/dal/db/mysql/ent/token"
	"kcers/biz/dal/db/mysql/ent/user"
	"kcers/biz/dal/db/mysql/ent/venue"
	"kcers/biz/dal/db/mysql/ent/venueplace"
	"kcers/idl_gen/model/base"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apiMixin := schema.API{}.Mixin()
	apiMixinFields0 := apiMixin[0].Fields()
	_ = apiMixinFields0
	apiFields := schema.API{}.Fields()
	_ = apiFields
	// apiDescCreatedAt is the schema descriptor for created_at field.
	apiDescCreatedAt := apiMixinFields0[1].Descriptor()
	// api.DefaultCreatedAt holds the default value on creation for the created_at field.
	api.DefaultCreatedAt = apiDescCreatedAt.Default.(func() time.Time)
	// apiDescUpdatedAt is the schema descriptor for updated_at field.
	apiDescUpdatedAt := apiMixinFields0[2].Descriptor()
	// api.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	api.DefaultUpdatedAt = apiDescUpdatedAt.Default.(func() time.Time)
	// api.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	api.UpdateDefaultUpdatedAt = apiDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apiDescDelete is the schema descriptor for delete field.
	apiDescDelete := apiMixinFields0[3].Descriptor()
	// api.DefaultDelete holds the default value on creation for the delete field.
	api.DefaultDelete = apiDescDelete.Default.(int64)
	// apiDescCreatedID is the schema descriptor for created_id field.
	apiDescCreatedID := apiMixinFields0[4].Descriptor()
	// api.DefaultCreatedID holds the default value on creation for the created_id field.
	api.DefaultCreatedID = apiDescCreatedID.Default.(int64)
	// apiDescMethod is the schema descriptor for method field.
	apiDescMethod := apiFields[4].Descriptor()
	// api.DefaultMethod holds the default value on creation for the method field.
	api.DefaultMethod = apiDescMethod.Default.(string)
	bannerMixin := schema.Banner{}.Mixin()
	bannerMixinFields0 := bannerMixin[0].Fields()
	_ = bannerMixinFields0
	bannerMixinFields1 := bannerMixin[1].Fields()
	_ = bannerMixinFields1
	bannerFields := schema.Banner{}.Fields()
	_ = bannerFields
	// bannerDescCreatedAt is the schema descriptor for created_at field.
	bannerDescCreatedAt := bannerMixinFields0[1].Descriptor()
	// banner.DefaultCreatedAt holds the default value on creation for the created_at field.
	banner.DefaultCreatedAt = bannerDescCreatedAt.Default.(func() time.Time)
	// bannerDescUpdatedAt is the schema descriptor for updated_at field.
	bannerDescUpdatedAt := bannerMixinFields0[2].Descriptor()
	// banner.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	banner.DefaultUpdatedAt = bannerDescUpdatedAt.Default.(func() time.Time)
	// banner.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	banner.UpdateDefaultUpdatedAt = bannerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bannerDescDelete is the schema descriptor for delete field.
	bannerDescDelete := bannerMixinFields0[3].Descriptor()
	// banner.DefaultDelete holds the default value on creation for the delete field.
	banner.DefaultDelete = bannerDescDelete.Default.(int64)
	// bannerDescCreatedID is the schema descriptor for created_id field.
	bannerDescCreatedID := bannerMixinFields0[4].Descriptor()
	// banner.DefaultCreatedID holds the default value on creation for the created_id field.
	banner.DefaultCreatedID = bannerDescCreatedID.Default.(int64)
	// bannerDescStatus is the schema descriptor for status field.
	bannerDescStatus := bannerMixinFields1[0].Descriptor()
	// banner.DefaultStatus holds the default value on creation for the status field.
	banner.DefaultStatus = bannerDescStatus.Default.(int64)
	// bannerDescIsShow is the schema descriptor for is_show field.
	bannerDescIsShow := bannerFields[3].Descriptor()
	// banner.DefaultIsShow holds the default value on creation for the is_show field.
	banner.DefaultIsShow = bannerDescIsShow.Default.(int64)
	contractMixin := schema.Contract{}.Mixin()
	contractMixinFields0 := contractMixin[0].Fields()
	_ = contractMixinFields0
	contractMixinFields1 := contractMixin[1].Fields()
	_ = contractMixinFields1
	contractFields := schema.Contract{}.Fields()
	_ = contractFields
	// contractDescCreatedAt is the schema descriptor for created_at field.
	contractDescCreatedAt := contractMixinFields0[1].Descriptor()
	// contract.DefaultCreatedAt holds the default value on creation for the created_at field.
	contract.DefaultCreatedAt = contractDescCreatedAt.Default.(func() time.Time)
	// contractDescUpdatedAt is the schema descriptor for updated_at field.
	contractDescUpdatedAt := contractMixinFields0[2].Descriptor()
	// contract.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	contract.DefaultUpdatedAt = contractDescUpdatedAt.Default.(func() time.Time)
	// contract.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	contract.UpdateDefaultUpdatedAt = contractDescUpdatedAt.UpdateDefault.(func() time.Time)
	// contractDescDelete is the schema descriptor for delete field.
	contractDescDelete := contractMixinFields0[3].Descriptor()
	// contract.DefaultDelete holds the default value on creation for the delete field.
	contract.DefaultDelete = contractDescDelete.Default.(int64)
	// contractDescCreatedID is the schema descriptor for created_id field.
	contractDescCreatedID := contractMixinFields0[4].Descriptor()
	// contract.DefaultCreatedID holds the default value on creation for the created_id field.
	contract.DefaultCreatedID = contractDescCreatedID.Default.(int64)
	// contractDescStatus is the schema descriptor for status field.
	contractDescStatus := contractMixinFields1[0].Descriptor()
	// contract.DefaultStatus holds the default value on creation for the status field.
	contract.DefaultStatus = contractDescStatus.Default.(int64)
	dictionaryMixin := schema.Dictionary{}.Mixin()
	dictionaryMixinFields0 := dictionaryMixin[0].Fields()
	_ = dictionaryMixinFields0
	dictionaryMixinFields1 := dictionaryMixin[1].Fields()
	_ = dictionaryMixinFields1
	dictionaryFields := schema.Dictionary{}.Fields()
	_ = dictionaryFields
	// dictionaryDescCreatedAt is the schema descriptor for created_at field.
	dictionaryDescCreatedAt := dictionaryMixinFields0[1].Descriptor()
	// dictionary.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionary.DefaultCreatedAt = dictionaryDescCreatedAt.Default.(func() time.Time)
	// dictionaryDescUpdatedAt is the schema descriptor for updated_at field.
	dictionaryDescUpdatedAt := dictionaryMixinFields0[2].Descriptor()
	// dictionary.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionary.DefaultUpdatedAt = dictionaryDescUpdatedAt.Default.(func() time.Time)
	// dictionary.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dictionary.UpdateDefaultUpdatedAt = dictionaryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dictionaryDescDelete is the schema descriptor for delete field.
	dictionaryDescDelete := dictionaryMixinFields0[3].Descriptor()
	// dictionary.DefaultDelete holds the default value on creation for the delete field.
	dictionary.DefaultDelete = dictionaryDescDelete.Default.(int64)
	// dictionaryDescCreatedID is the schema descriptor for created_id field.
	dictionaryDescCreatedID := dictionaryMixinFields0[4].Descriptor()
	// dictionary.DefaultCreatedID holds the default value on creation for the created_id field.
	dictionary.DefaultCreatedID = dictionaryDescCreatedID.Default.(int64)
	// dictionaryDescStatus is the schema descriptor for status field.
	dictionaryDescStatus := dictionaryMixinFields1[0].Descriptor()
	// dictionary.DefaultStatus holds the default value on creation for the status field.
	dictionary.DefaultStatus = dictionaryDescStatus.Default.(int64)
	dictionarydetailMixin := schema.DictionaryDetail{}.Mixin()
	dictionarydetailMixinFields0 := dictionarydetailMixin[0].Fields()
	_ = dictionarydetailMixinFields0
	dictionarydetailMixinFields1 := dictionarydetailMixin[1].Fields()
	_ = dictionarydetailMixinFields1
	dictionarydetailFields := schema.DictionaryDetail{}.Fields()
	_ = dictionarydetailFields
	// dictionarydetailDescCreatedAt is the schema descriptor for created_at field.
	dictionarydetailDescCreatedAt := dictionarydetailMixinFields0[1].Descriptor()
	// dictionarydetail.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionarydetail.DefaultCreatedAt = dictionarydetailDescCreatedAt.Default.(func() time.Time)
	// dictionarydetailDescUpdatedAt is the schema descriptor for updated_at field.
	dictionarydetailDescUpdatedAt := dictionarydetailMixinFields0[2].Descriptor()
	// dictionarydetail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionarydetail.DefaultUpdatedAt = dictionarydetailDescUpdatedAt.Default.(func() time.Time)
	// dictionarydetail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dictionarydetail.UpdateDefaultUpdatedAt = dictionarydetailDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dictionarydetailDescDelete is the schema descriptor for delete field.
	dictionarydetailDescDelete := dictionarydetailMixinFields0[3].Descriptor()
	// dictionarydetail.DefaultDelete holds the default value on creation for the delete field.
	dictionarydetail.DefaultDelete = dictionarydetailDescDelete.Default.(int64)
	// dictionarydetailDescCreatedID is the schema descriptor for created_id field.
	dictionarydetailDescCreatedID := dictionarydetailMixinFields0[4].Descriptor()
	// dictionarydetail.DefaultCreatedID holds the default value on creation for the created_id field.
	dictionarydetail.DefaultCreatedID = dictionarydetailDescCreatedID.Default.(int64)
	// dictionarydetailDescStatus is the schema descriptor for status field.
	dictionarydetailDescStatus := dictionarydetailMixinFields1[0].Descriptor()
	// dictionarydetail.DefaultStatus holds the default value on creation for the status field.
	dictionarydetail.DefaultStatus = dictionarydetailDescStatus.Default.(int64)
	entrylogsMixin := schema.EntryLogs{}.Mixin()
	entrylogsMixinFields0 := entrylogsMixin[0].Fields()
	_ = entrylogsMixinFields0
	entrylogsFields := schema.EntryLogs{}.Fields()
	_ = entrylogsFields
	// entrylogsDescCreatedAt is the schema descriptor for created_at field.
	entrylogsDescCreatedAt := entrylogsMixinFields0[1].Descriptor()
	// entrylogs.DefaultCreatedAt holds the default value on creation for the created_at field.
	entrylogs.DefaultCreatedAt = entrylogsDescCreatedAt.Default.(func() time.Time)
	// entrylogsDescUpdatedAt is the schema descriptor for updated_at field.
	entrylogsDescUpdatedAt := entrylogsMixinFields0[2].Descriptor()
	// entrylogs.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entrylogs.DefaultUpdatedAt = entrylogsDescUpdatedAt.Default.(func() time.Time)
	// entrylogs.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entrylogs.UpdateDefaultUpdatedAt = entrylogsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entrylogsDescDelete is the schema descriptor for delete field.
	entrylogsDescDelete := entrylogsMixinFields0[3].Descriptor()
	// entrylogs.DefaultDelete holds the default value on creation for the delete field.
	entrylogs.DefaultDelete = entrylogsDescDelete.Default.(int64)
	// entrylogsDescCreatedID is the schema descriptor for created_id field.
	entrylogsDescCreatedID := entrylogsMixinFields0[4].Descriptor()
	// entrylogs.DefaultCreatedID holds the default value on creation for the created_id field.
	entrylogs.DefaultCreatedID = entrylogsDescCreatedID.Default.(int64)
	// entrylogsDescMemberID is the schema descriptor for member_id field.
	entrylogsDescMemberID := entrylogsFields[0].Descriptor()
	// entrylogs.DefaultMemberID holds the default value on creation for the member_id field.
	entrylogs.DefaultMemberID = entrylogsDescMemberID.Default.(int64)
	// entrylogsDescUserID is the schema descriptor for user_id field.
	entrylogsDescUserID := entrylogsFields[1].Descriptor()
	// entrylogs.DefaultUserID holds the default value on creation for the user_id field.
	entrylogs.DefaultUserID = entrylogsDescUserID.Default.(int64)
	faceMixin := schema.Face{}.Mixin()
	faceMixinFields0 := faceMixin[0].Fields()
	_ = faceMixinFields0
	faceFields := schema.Face{}.Fields()
	_ = faceFields
	// faceDescCreatedAt is the schema descriptor for created_at field.
	faceDescCreatedAt := faceMixinFields0[1].Descriptor()
	// face.DefaultCreatedAt holds the default value on creation for the created_at field.
	face.DefaultCreatedAt = faceDescCreatedAt.Default.(func() time.Time)
	// faceDescUpdatedAt is the schema descriptor for updated_at field.
	faceDescUpdatedAt := faceMixinFields0[2].Descriptor()
	// face.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	face.DefaultUpdatedAt = faceDescUpdatedAt.Default.(func() time.Time)
	// face.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	face.UpdateDefaultUpdatedAt = faceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// faceDescDelete is the schema descriptor for delete field.
	faceDescDelete := faceMixinFields0[3].Descriptor()
	// face.DefaultDelete holds the default value on creation for the delete field.
	face.DefaultDelete = faceDescDelete.Default.(int64)
	// faceDescCreatedID is the schema descriptor for created_id field.
	faceDescCreatedID := faceMixinFields0[4].Descriptor()
	// face.DefaultCreatedID holds the default value on creation for the created_id field.
	face.DefaultCreatedID = faceDescCreatedID.Default.(int64)
	// faceDescFaceIdentityCard is the schema descriptor for face_identity_card field.
	faceDescFaceIdentityCard := faceFields[3].Descriptor()
	// face.DefaultFaceIdentityCard holds the default value on creation for the face_identity_card field.
	face.DefaultFaceIdentityCard = faceDescFaceIdentityCard.Default.(string)
	// faceDescBackIdentityCard is the schema descriptor for back_identity_card field.
	faceDescBackIdentityCard := faceFields[4].Descriptor()
	// face.DefaultBackIdentityCard holds the default value on creation for the back_identity_card field.
	face.DefaultBackIdentityCard = faceDescBackIdentityCard.Default.(string)
	// faceDescFacePic is the schema descriptor for face_pic field.
	faceDescFacePic := faceFields[5].Descriptor()
	// face.DefaultFacePic holds the default value on creation for the face_pic field.
	face.DefaultFacePic = faceDescFacePic.Default.(string)
	// faceDescFaceEigenvalue is the schema descriptor for face_eigenvalue field.
	faceDescFaceEigenvalue := faceFields[6].Descriptor()
	// face.DefaultFaceEigenvalue holds the default value on creation for the face_eigenvalue field.
	face.DefaultFaceEigenvalue = faceDescFaceEigenvalue.Default.(string)
	// faceDescFacePicUpdatedAt is the schema descriptor for face_pic_updated_at field.
	faceDescFacePicUpdatedAt := faceFields[7].Descriptor()
	// face.DefaultFacePicUpdatedAt holds the default value on creation for the face_pic_updated_at field.
	face.DefaultFacePicUpdatedAt = faceDescFacePicUpdatedAt.Default.(func() time.Time)
	logsMixin := schema.Logs{}.Mixin()
	logsMixinFields0 := logsMixin[0].Fields()
	_ = logsMixinFields0
	logsFields := schema.Logs{}.Fields()
	_ = logsFields
	// logsDescCreatedAt is the schema descriptor for created_at field.
	logsDescCreatedAt := logsMixinFields0[1].Descriptor()
	// logs.DefaultCreatedAt holds the default value on creation for the created_at field.
	logs.DefaultCreatedAt = logsDescCreatedAt.Default.(func() time.Time)
	// logsDescUpdatedAt is the schema descriptor for updated_at field.
	logsDescUpdatedAt := logsMixinFields0[2].Descriptor()
	// logs.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	logs.DefaultUpdatedAt = logsDescUpdatedAt.Default.(func() time.Time)
	// logs.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	logs.UpdateDefaultUpdatedAt = logsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// logsDescDelete is the schema descriptor for delete field.
	logsDescDelete := logsMixinFields0[3].Descriptor()
	// logs.DefaultDelete holds the default value on creation for the delete field.
	logs.DefaultDelete = logsDescDelete.Default.(int64)
	// logsDescCreatedID is the schema descriptor for created_id field.
	logsDescCreatedID := logsMixinFields0[4].Descriptor()
	// logs.DefaultCreatedID holds the default value on creation for the created_id field.
	logs.DefaultCreatedID = logsDescCreatedID.Default.(int64)
	memberMixin := schema.Member{}.Mixin()
	memberMixinFields0 := memberMixin[0].Fields()
	_ = memberMixinFields0
	memberMixinFields1 := memberMixin[1].Fields()
	_ = memberMixinFields1
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescCreatedAt is the schema descriptor for created_at field.
	memberDescCreatedAt := memberMixinFields0[1].Descriptor()
	// member.DefaultCreatedAt holds the default value on creation for the created_at field.
	member.DefaultCreatedAt = memberDescCreatedAt.Default.(func() time.Time)
	// memberDescUpdatedAt is the schema descriptor for updated_at field.
	memberDescUpdatedAt := memberMixinFields0[2].Descriptor()
	// member.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	member.DefaultUpdatedAt = memberDescUpdatedAt.Default.(func() time.Time)
	// member.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	member.UpdateDefaultUpdatedAt = memberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memberDescDelete is the schema descriptor for delete field.
	memberDescDelete := memberMixinFields0[3].Descriptor()
	// member.DefaultDelete holds the default value on creation for the delete field.
	member.DefaultDelete = memberDescDelete.Default.(int64)
	// memberDescCreatedID is the schema descriptor for created_id field.
	memberDescCreatedID := memberMixinFields0[4].Descriptor()
	// member.DefaultCreatedID holds the default value on creation for the created_id field.
	member.DefaultCreatedID = memberDescCreatedID.Default.(int64)
	// memberDescStatus is the schema descriptor for status field.
	memberDescStatus := memberMixinFields1[0].Descriptor()
	// member.DefaultStatus holds the default value on creation for the status field.
	member.DefaultStatus = memberDescStatus.Default.(int64)
	// memberDescAvatar is the schema descriptor for avatar field.
	memberDescAvatar := memberFields[4].Descriptor()
	// member.DefaultAvatar holds the default value on creation for the avatar field.
	member.DefaultAvatar = memberDescAvatar.Default.(string)
	// memberDescCondition is the schema descriptor for condition field.
	memberDescCondition := memberFields[5].Descriptor()
	// member.DefaultCondition holds the default value on creation for the condition field.
	member.DefaultCondition = memberDescCondition.Default.(int64)
	membercontractMixin := schema.MemberContract{}.Mixin()
	membercontractMixinFields0 := membercontractMixin[0].Fields()
	_ = membercontractMixinFields0
	membercontractMixinFields1 := membercontractMixin[1].Fields()
	_ = membercontractMixinFields1
	membercontractFields := schema.MemberContract{}.Fields()
	_ = membercontractFields
	// membercontractDescCreatedAt is the schema descriptor for created_at field.
	membercontractDescCreatedAt := membercontractMixinFields0[1].Descriptor()
	// membercontract.DefaultCreatedAt holds the default value on creation for the created_at field.
	membercontract.DefaultCreatedAt = membercontractDescCreatedAt.Default.(func() time.Time)
	// membercontractDescUpdatedAt is the schema descriptor for updated_at field.
	membercontractDescUpdatedAt := membercontractMixinFields0[2].Descriptor()
	// membercontract.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membercontract.DefaultUpdatedAt = membercontractDescUpdatedAt.Default.(func() time.Time)
	// membercontract.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membercontract.UpdateDefaultUpdatedAt = membercontractDescUpdatedAt.UpdateDefault.(func() time.Time)
	// membercontractDescDelete is the schema descriptor for delete field.
	membercontractDescDelete := membercontractMixinFields0[3].Descriptor()
	// membercontract.DefaultDelete holds the default value on creation for the delete field.
	membercontract.DefaultDelete = membercontractDescDelete.Default.(int64)
	// membercontractDescCreatedID is the schema descriptor for created_id field.
	membercontractDescCreatedID := membercontractMixinFields0[4].Descriptor()
	// membercontract.DefaultCreatedID holds the default value on creation for the created_id field.
	membercontract.DefaultCreatedID = membercontractDescCreatedID.Default.(int64)
	// membercontractDescStatus is the schema descriptor for status field.
	membercontractDescStatus := membercontractMixinFields1[0].Descriptor()
	// membercontract.DefaultStatus holds the default value on creation for the status field.
	membercontract.DefaultStatus = membercontractDescStatus.Default.(int64)
	membercontractcontentMixin := schema.MemberContractContent{}.Mixin()
	membercontractcontentMixinFields0 := membercontractcontentMixin[0].Fields()
	_ = membercontractcontentMixinFields0
	membercontractcontentFields := schema.MemberContractContent{}.Fields()
	_ = membercontractcontentFields
	// membercontractcontentDescCreatedAt is the schema descriptor for created_at field.
	membercontractcontentDescCreatedAt := membercontractcontentMixinFields0[1].Descriptor()
	// membercontractcontent.DefaultCreatedAt holds the default value on creation for the created_at field.
	membercontractcontent.DefaultCreatedAt = membercontractcontentDescCreatedAt.Default.(func() time.Time)
	// membercontractcontentDescUpdatedAt is the schema descriptor for updated_at field.
	membercontractcontentDescUpdatedAt := membercontractcontentMixinFields0[2].Descriptor()
	// membercontractcontent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membercontractcontent.DefaultUpdatedAt = membercontractcontentDescUpdatedAt.Default.(func() time.Time)
	// membercontractcontent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membercontractcontent.UpdateDefaultUpdatedAt = membercontractcontentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// membercontractcontentDescDelete is the schema descriptor for delete field.
	membercontractcontentDescDelete := membercontractcontentMixinFields0[3].Descriptor()
	// membercontractcontent.DefaultDelete holds the default value on creation for the delete field.
	membercontractcontent.DefaultDelete = membercontractcontentDescDelete.Default.(int64)
	// membercontractcontentDescCreatedID is the schema descriptor for created_id field.
	membercontractcontentDescCreatedID := membercontractcontentMixinFields0[4].Descriptor()
	// membercontractcontent.DefaultCreatedID holds the default value on creation for the created_id field.
	membercontractcontent.DefaultCreatedID = membercontractcontentDescCreatedID.Default.(int64)
	memberdetailsMixin := schema.MemberDetails{}.Mixin()
	memberdetailsMixinFields0 := memberdetailsMixin[0].Fields()
	_ = memberdetailsMixinFields0
	memberdetailsFields := schema.MemberDetails{}.Fields()
	_ = memberdetailsFields
	// memberdetailsDescCreatedAt is the schema descriptor for created_at field.
	memberdetailsDescCreatedAt := memberdetailsMixinFields0[1].Descriptor()
	// memberdetails.DefaultCreatedAt holds the default value on creation for the created_at field.
	memberdetails.DefaultCreatedAt = memberdetailsDescCreatedAt.Default.(func() time.Time)
	// memberdetailsDescUpdatedAt is the schema descriptor for updated_at field.
	memberdetailsDescUpdatedAt := memberdetailsMixinFields0[2].Descriptor()
	// memberdetails.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	memberdetails.DefaultUpdatedAt = memberdetailsDescUpdatedAt.Default.(func() time.Time)
	// memberdetails.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	memberdetails.UpdateDefaultUpdatedAt = memberdetailsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memberdetailsDescDelete is the schema descriptor for delete field.
	memberdetailsDescDelete := memberdetailsMixinFields0[3].Descriptor()
	// memberdetails.DefaultDelete holds the default value on creation for the delete field.
	memberdetails.DefaultDelete = memberdetailsDescDelete.Default.(int64)
	// memberdetailsDescCreatedID is the schema descriptor for created_id field.
	memberdetailsDescCreatedID := memberdetailsMixinFields0[4].Descriptor()
	// memberdetails.DefaultCreatedID holds the default value on creation for the created_id field.
	memberdetails.DefaultCreatedID = memberdetailsDescCreatedID.Default.(int64)
	// memberdetailsDescMoneySum is the schema descriptor for money_sum field.
	memberdetailsDescMoneySum := memberdetailsFields[1].Descriptor()
	// memberdetails.DefaultMoneySum holds the default value on creation for the money_sum field.
	memberdetails.DefaultMoneySum = memberdetailsDescMoneySum.Default.(float64)
	// memberdetailsDescProductID is the schema descriptor for product_id field.
	memberdetailsDescProductID := memberdetailsFields[2].Descriptor()
	// memberdetails.DefaultProductID holds the default value on creation for the product_id field.
	memberdetails.DefaultProductID = memberdetailsDescProductID.Default.(int64)
	// memberdetailsDescEntrySum is the schema descriptor for entry_sum field.
	memberdetailsDescEntrySum := memberdetailsFields[4].Descriptor()
	// memberdetails.DefaultEntrySum holds the default value on creation for the entry_sum field.
	memberdetails.DefaultEntrySum = memberdetailsDescEntrySum.Default.(int64)
	membernoteMixin := schema.MemberNote{}.Mixin()
	membernoteMixinFields0 := membernoteMixin[0].Fields()
	_ = membernoteMixinFields0
	membernoteMixinFields1 := membernoteMixin[1].Fields()
	_ = membernoteMixinFields1
	membernoteFields := schema.MemberNote{}.Fields()
	_ = membernoteFields
	// membernoteDescCreatedAt is the schema descriptor for created_at field.
	membernoteDescCreatedAt := membernoteMixinFields0[1].Descriptor()
	// membernote.DefaultCreatedAt holds the default value on creation for the created_at field.
	membernote.DefaultCreatedAt = membernoteDescCreatedAt.Default.(func() time.Time)
	// membernoteDescUpdatedAt is the schema descriptor for updated_at field.
	membernoteDescUpdatedAt := membernoteMixinFields0[2].Descriptor()
	// membernote.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membernote.DefaultUpdatedAt = membernoteDescUpdatedAt.Default.(func() time.Time)
	// membernote.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membernote.UpdateDefaultUpdatedAt = membernoteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// membernoteDescDelete is the schema descriptor for delete field.
	membernoteDescDelete := membernoteMixinFields0[3].Descriptor()
	// membernote.DefaultDelete holds the default value on creation for the delete field.
	membernote.DefaultDelete = membernoteDescDelete.Default.(int64)
	// membernoteDescCreatedID is the schema descriptor for created_id field.
	membernoteDescCreatedID := membernoteMixinFields0[4].Descriptor()
	// membernote.DefaultCreatedID holds the default value on creation for the created_id field.
	membernote.DefaultCreatedID = membernoteDescCreatedID.Default.(int64)
	// membernoteDescStatus is the schema descriptor for status field.
	membernoteDescStatus := membernoteMixinFields1[0].Descriptor()
	// membernote.DefaultStatus holds the default value on creation for the status field.
	membernote.DefaultStatus = membernoteDescStatus.Default.(int64)
	// membernoteDescNote is the schema descriptor for note field.
	membernoteDescNote := membernoteFields[1].Descriptor()
	// membernote.DefaultNote holds the default value on creation for the note field.
	membernote.DefaultNote = membernoteDescNote.Default.(string)
	memberproductMixin := schema.MemberProduct{}.Mixin()
	memberproductMixinFields0 := memberproductMixin[0].Fields()
	_ = memberproductMixinFields0
	memberproductMixinFields1 := memberproductMixin[1].Fields()
	_ = memberproductMixinFields1
	memberproductFields := schema.MemberProduct{}.Fields()
	_ = memberproductFields
	// memberproductDescCreatedAt is the schema descriptor for created_at field.
	memberproductDescCreatedAt := memberproductMixinFields0[1].Descriptor()
	// memberproduct.DefaultCreatedAt holds the default value on creation for the created_at field.
	memberproduct.DefaultCreatedAt = memberproductDescCreatedAt.Default.(func() time.Time)
	// memberproductDescUpdatedAt is the schema descriptor for updated_at field.
	memberproductDescUpdatedAt := memberproductMixinFields0[2].Descriptor()
	// memberproduct.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	memberproduct.DefaultUpdatedAt = memberproductDescUpdatedAt.Default.(func() time.Time)
	// memberproduct.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	memberproduct.UpdateDefaultUpdatedAt = memberproductDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memberproductDescDelete is the schema descriptor for delete field.
	memberproductDescDelete := memberproductMixinFields0[3].Descriptor()
	// memberproduct.DefaultDelete holds the default value on creation for the delete field.
	memberproduct.DefaultDelete = memberproductDescDelete.Default.(int64)
	// memberproductDescCreatedID is the schema descriptor for created_id field.
	memberproductDescCreatedID := memberproductMixinFields0[4].Descriptor()
	// memberproduct.DefaultCreatedID holds the default value on creation for the created_id field.
	memberproduct.DefaultCreatedID = memberproductDescCreatedID.Default.(int64)
	// memberproductDescStatus is the schema descriptor for status field.
	memberproductDescStatus := memberproductMixinFields1[0].Descriptor()
	// memberproduct.DefaultStatus holds the default value on creation for the status field.
	memberproduct.DefaultStatus = memberproductDescStatus.Default.(int64)
	memberproductpropertyMixin := schema.MemberProductProperty{}.Mixin()
	memberproductpropertyMixinFields0 := memberproductpropertyMixin[0].Fields()
	_ = memberproductpropertyMixinFields0
	memberproductpropertyMixinFields1 := memberproductpropertyMixin[1].Fields()
	_ = memberproductpropertyMixinFields1
	memberproductpropertyFields := schema.MemberProductProperty{}.Fields()
	_ = memberproductpropertyFields
	// memberproductpropertyDescCreatedAt is the schema descriptor for created_at field.
	memberproductpropertyDescCreatedAt := memberproductpropertyMixinFields0[1].Descriptor()
	// memberproductproperty.DefaultCreatedAt holds the default value on creation for the created_at field.
	memberproductproperty.DefaultCreatedAt = memberproductpropertyDescCreatedAt.Default.(func() time.Time)
	// memberproductpropertyDescUpdatedAt is the schema descriptor for updated_at field.
	memberproductpropertyDescUpdatedAt := memberproductpropertyMixinFields0[2].Descriptor()
	// memberproductproperty.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	memberproductproperty.DefaultUpdatedAt = memberproductpropertyDescUpdatedAt.Default.(func() time.Time)
	// memberproductproperty.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	memberproductproperty.UpdateDefaultUpdatedAt = memberproductpropertyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memberproductpropertyDescDelete is the schema descriptor for delete field.
	memberproductpropertyDescDelete := memberproductpropertyMixinFields0[3].Descriptor()
	// memberproductproperty.DefaultDelete holds the default value on creation for the delete field.
	memberproductproperty.DefaultDelete = memberproductpropertyDescDelete.Default.(int64)
	// memberproductpropertyDescCreatedID is the schema descriptor for created_id field.
	memberproductpropertyDescCreatedID := memberproductpropertyMixinFields0[4].Descriptor()
	// memberproductproperty.DefaultCreatedID holds the default value on creation for the created_id field.
	memberproductproperty.DefaultCreatedID = memberproductpropertyDescCreatedID.Default.(int64)
	// memberproductpropertyDescStatus is the schema descriptor for status field.
	memberproductpropertyDescStatus := memberproductpropertyMixinFields1[0].Descriptor()
	// memberproductproperty.DefaultStatus holds the default value on creation for the status field.
	memberproductproperty.DefaultStatus = memberproductpropertyDescStatus.Default.(int64)
	// memberproductpropertyDescCount is the schema descriptor for count field.
	memberproductpropertyDescCount := memberproductpropertyFields[8].Descriptor()
	// memberproductproperty.DefaultCount holds the default value on creation for the count field.
	memberproductproperty.DefaultCount = memberproductpropertyDescCount.Default.(int64)
	// memberproductpropertyDescCountSurplus is the schema descriptor for count_surplus field.
	memberproductpropertyDescCountSurplus := memberproductpropertyFields[9].Descriptor()
	// memberproductproperty.DefaultCountSurplus holds the default value on creation for the count_surplus field.
	memberproductproperty.DefaultCountSurplus = memberproductpropertyDescCountSurplus.Default.(int64)
	memberprofileMixin := schema.MemberProfile{}.Mixin()
	memberprofileMixinFields0 := memberprofileMixin[0].Fields()
	_ = memberprofileMixinFields0
	memberprofileFields := schema.MemberProfile{}.Fields()
	_ = memberprofileFields
	// memberprofileDescCreatedAt is the schema descriptor for created_at field.
	memberprofileDescCreatedAt := memberprofileMixinFields0[1].Descriptor()
	// memberprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	memberprofile.DefaultCreatedAt = memberprofileDescCreatedAt.Default.(func() time.Time)
	// memberprofileDescUpdatedAt is the schema descriptor for updated_at field.
	memberprofileDescUpdatedAt := memberprofileMixinFields0[2].Descriptor()
	// memberprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	memberprofile.DefaultUpdatedAt = memberprofileDescUpdatedAt.Default.(func() time.Time)
	// memberprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	memberprofile.UpdateDefaultUpdatedAt = memberprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memberprofileDescDelete is the schema descriptor for delete field.
	memberprofileDescDelete := memberprofileMixinFields0[3].Descriptor()
	// memberprofile.DefaultDelete holds the default value on creation for the delete field.
	memberprofile.DefaultDelete = memberprofileDescDelete.Default.(int64)
	// memberprofileDescCreatedID is the schema descriptor for created_id field.
	memberprofileDescCreatedID := memberprofileMixinFields0[4].Descriptor()
	// memberprofile.DefaultCreatedID holds the default value on creation for the created_id field.
	memberprofile.DefaultCreatedID = memberprofileDescCreatedID.Default.(int64)
	// memberprofileDescIntention is the schema descriptor for intention field.
	memberprofileDescIntention := memberprofileFields[0].Descriptor()
	// memberprofile.DefaultIntention holds the default value on creation for the intention field.
	memberprofile.DefaultIntention = memberprofileDescIntention.Default.(int64)
	// memberprofileDescSource is the schema descriptor for source field.
	memberprofileDescSource := memberprofileFields[1].Descriptor()
	// memberprofile.DefaultSource holds the default value on creation for the source field.
	memberprofile.DefaultSource = memberprofileDescSource.Default.(int64)
	// memberprofileDescGender is the schema descriptor for gender field.
	memberprofileDescGender := memberprofileFields[3].Descriptor()
	// memberprofile.DefaultGender holds the default value on creation for the gender field.
	memberprofile.DefaultGender = memberprofileDescGender.Default.(int64)
	// memberprofileDescRelationMid is the schema descriptor for relation_mid field.
	memberprofileDescRelationMid := memberprofileFields[7].Descriptor()
	// memberprofile.DefaultRelationMid holds the default value on creation for the relation_mid field.
	memberprofile.DefaultRelationMid = memberprofileDescRelationMid.Default.(int64)
	// memberprofileDescRelationUID is the schema descriptor for relation_uid field.
	memberprofileDescRelationUID := memberprofileFields[9].Descriptor()
	// memberprofile.DefaultRelationUID holds the default value on creation for the relation_uid field.
	memberprofile.DefaultRelationUID = memberprofileDescRelationUID.Default.(int64)
	membertokenMixin := schema.MemberToken{}.Mixin()
	membertokenMixinFields0 := membertokenMixin[0].Fields()
	_ = membertokenMixinFields0
	membertokenFields := schema.MemberToken{}.Fields()
	_ = membertokenFields
	// membertokenDescCreatedAt is the schema descriptor for created_at field.
	membertokenDescCreatedAt := membertokenMixinFields0[1].Descriptor()
	// membertoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	membertoken.DefaultCreatedAt = membertokenDescCreatedAt.Default.(func() time.Time)
	// membertokenDescUpdatedAt is the schema descriptor for updated_at field.
	membertokenDescUpdatedAt := membertokenMixinFields0[2].Descriptor()
	// membertoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membertoken.DefaultUpdatedAt = membertokenDescUpdatedAt.Default.(func() time.Time)
	// membertoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membertoken.UpdateDefaultUpdatedAt = membertokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// membertokenDescDelete is the schema descriptor for delete field.
	membertokenDescDelete := membertokenMixinFields0[3].Descriptor()
	// membertoken.DefaultDelete holds the default value on creation for the delete field.
	membertoken.DefaultDelete = membertokenDescDelete.Default.(int64)
	// membertokenDescCreatedID is the schema descriptor for created_id field.
	membertokenDescCreatedID := membertokenMixinFields0[4].Descriptor()
	// membertoken.DefaultCreatedID holds the default value on creation for the created_id field.
	membertoken.DefaultCreatedID = membertokenDescCreatedID.Default.(int64)
	menuMixin := schema.Menu{}.Mixin()
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuMixinFields0[1].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdatedAt is the schema descriptor for updated_at field.
	menuDescUpdatedAt := menuMixinFields0[2].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menu.UpdateDefaultUpdatedAt = menuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuDescDelete is the schema descriptor for delete field.
	menuDescDelete := menuMixinFields0[3].Descriptor()
	// menu.DefaultDelete holds the default value on creation for the delete field.
	menu.DefaultDelete = menuDescDelete.Default.(int64)
	// menuDescCreatedID is the schema descriptor for created_id field.
	menuDescCreatedID := menuMixinFields0[4].Descriptor()
	// menu.DefaultCreatedID holds the default value on creation for the created_id field.
	menu.DefaultCreatedID = menuDescCreatedID.Default.(int64)
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[1].Descriptor()
	// menu.DefaultPath holds the default value on creation for the path field.
	menu.DefaultPath = menuDescPath.Default.(string)
	// menuDescOrderNo is the schema descriptor for order_no field.
	menuDescOrderNo := menuFields[3].Descriptor()
	// menu.DefaultOrderNo holds the default value on creation for the order_no field.
	menu.DefaultOrderNo = menuDescOrderNo.Default.(int64)
	// menuDescDisabled is the schema descriptor for disabled field.
	menuDescDisabled := menuFields[4].Descriptor()
	// menu.DefaultDisabled holds the default value on creation for the disabled field.
	menu.DefaultDisabled = menuDescDisabled.Default.(int64)
	// menuDescIgnore is the schema descriptor for ignore field.
	menuDescIgnore := menuFields[5].Descriptor()
	// menu.DefaultIgnore holds the default value on creation for the ignore field.
	menu.DefaultIgnore = menuDescIgnore.Default.(bool)
	menuparamMixin := schema.MenuParam{}.Mixin()
	menuparamMixinFields0 := menuparamMixin[0].Fields()
	_ = menuparamMixinFields0
	menuparamFields := schema.MenuParam{}.Fields()
	_ = menuparamFields
	// menuparamDescCreatedAt is the schema descriptor for created_at field.
	menuparamDescCreatedAt := menuparamMixinFields0[1].Descriptor()
	// menuparam.DefaultCreatedAt holds the default value on creation for the created_at field.
	menuparam.DefaultCreatedAt = menuparamDescCreatedAt.Default.(func() time.Time)
	// menuparamDescUpdatedAt is the schema descriptor for updated_at field.
	menuparamDescUpdatedAt := menuparamMixinFields0[2].Descriptor()
	// menuparam.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menuparam.DefaultUpdatedAt = menuparamDescUpdatedAt.Default.(func() time.Time)
	// menuparam.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menuparam.UpdateDefaultUpdatedAt = menuparamDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuparamDescDelete is the schema descriptor for delete field.
	menuparamDescDelete := menuparamMixinFields0[3].Descriptor()
	// menuparam.DefaultDelete holds the default value on creation for the delete field.
	menuparam.DefaultDelete = menuparamDescDelete.Default.(int64)
	// menuparamDescCreatedID is the schema descriptor for created_id field.
	menuparamDescCreatedID := menuparamMixinFields0[4].Descriptor()
	// menuparam.DefaultCreatedID holds the default value on creation for the created_id field.
	menuparam.DefaultCreatedID = menuparamDescCreatedID.Default.(int64)
	messagesMixin := schema.Messages{}.Mixin()
	messagesMixinFields0 := messagesMixin[0].Fields()
	_ = messagesMixinFields0
	messagesFields := schema.Messages{}.Fields()
	_ = messagesFields
	// messagesDescCreatedAt is the schema descriptor for created_at field.
	messagesDescCreatedAt := messagesMixinFields0[1].Descriptor()
	// messages.DefaultCreatedAt holds the default value on creation for the created_at field.
	messages.DefaultCreatedAt = messagesDescCreatedAt.Default.(func() time.Time)
	// messagesDescUpdatedAt is the schema descriptor for updated_at field.
	messagesDescUpdatedAt := messagesMixinFields0[2].Descriptor()
	// messages.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	messages.DefaultUpdatedAt = messagesDescUpdatedAt.Default.(func() time.Time)
	// messages.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	messages.UpdateDefaultUpdatedAt = messagesDescUpdatedAt.UpdateDefault.(func() time.Time)
	// messagesDescDelete is the schema descriptor for delete field.
	messagesDescDelete := messagesMixinFields0[3].Descriptor()
	// messages.DefaultDelete holds the default value on creation for the delete field.
	messages.DefaultDelete = messagesDescDelete.Default.(int64)
	// messagesDescCreatedID is the schema descriptor for created_id field.
	messagesDescCreatedID := messagesMixinFields0[4].Descriptor()
	// messages.DefaultCreatedID holds the default value on creation for the created_id field.
	messages.DefaultCreatedID = messagesDescCreatedID.Default.(int64)
	entorderMixin := schema.Order{}.Mixin()
	entorderMixinFields0 := entorderMixin[0].Fields()
	_ = entorderMixinFields0
	entorderFields := schema.Order{}.Fields()
	_ = entorderFields
	// entorderDescCreatedAt is the schema descriptor for created_at field.
	entorderDescCreatedAt := entorderMixinFields0[1].Descriptor()
	// entorder.DefaultCreatedAt holds the default value on creation for the created_at field.
	entorder.DefaultCreatedAt = entorderDescCreatedAt.Default.(func() time.Time)
	// entorderDescUpdatedAt is the schema descriptor for updated_at field.
	entorderDescUpdatedAt := entorderMixinFields0[2].Descriptor()
	// entorder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entorder.DefaultUpdatedAt = entorderDescUpdatedAt.Default.(func() time.Time)
	// entorder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entorder.UpdateDefaultUpdatedAt = entorderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entorderDescDelete is the schema descriptor for delete field.
	entorderDescDelete := entorderMixinFields0[3].Descriptor()
	// entorder.DefaultDelete holds the default value on creation for the delete field.
	entorder.DefaultDelete = entorderDescDelete.Default.(int64)
	// entorderDescCreatedID is the schema descriptor for created_id field.
	entorderDescCreatedID := entorderMixinFields0[4].Descriptor()
	// entorder.DefaultCreatedID holds the default value on creation for the created_id field.
	entorder.DefaultCreatedID = entorderDescCreatedID.Default.(int64)
	// entorderDescStatus is the schema descriptor for status field.
	entorderDescStatus := entorderFields[4].Descriptor()
	// entorder.DefaultStatus holds the default value on creation for the status field.
	entorder.DefaultStatus = entorderDescStatus.Default.(int64)
	// entorderDescSource is the schema descriptor for source field.
	entorderDescSource := entorderFields[5].Descriptor()
	// entorder.DefaultSource holds the default value on creation for the source field.
	entorder.DefaultSource = entorderDescSource.Default.(string)
	// entorderDescDevice is the schema descriptor for device field.
	entorderDescDevice := entorderFields[6].Descriptor()
	// entorder.DefaultDevice holds the default value on creation for the device field.
	entorder.DefaultDevice = entorderDescDevice.Default.(string)
	orderamountMixin := schema.OrderAmount{}.Mixin()
	orderamountMixinFields0 := orderamountMixin[0].Fields()
	_ = orderamountMixinFields0
	orderamountFields := schema.OrderAmount{}.Fields()
	_ = orderamountFields
	// orderamountDescCreatedAt is the schema descriptor for created_at field.
	orderamountDescCreatedAt := orderamountMixinFields0[1].Descriptor()
	// orderamount.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderamount.DefaultCreatedAt = orderamountDescCreatedAt.Default.(func() time.Time)
	// orderamountDescUpdatedAt is the schema descriptor for updated_at field.
	orderamountDescUpdatedAt := orderamountMixinFields0[2].Descriptor()
	// orderamount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderamount.DefaultUpdatedAt = orderamountDescUpdatedAt.Default.(func() time.Time)
	// orderamount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderamount.UpdateDefaultUpdatedAt = orderamountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderamountDescDelete is the schema descriptor for delete field.
	orderamountDescDelete := orderamountMixinFields0[3].Descriptor()
	// orderamount.DefaultDelete holds the default value on creation for the delete field.
	orderamount.DefaultDelete = orderamountDescDelete.Default.(int64)
	// orderamountDescCreatedID is the schema descriptor for created_id field.
	orderamountDescCreatedID := orderamountMixinFields0[4].Descriptor()
	// orderamount.DefaultCreatedID holds the default value on creation for the created_id field.
	orderamount.DefaultCreatedID = orderamountDescCreatedID.Default.(int64)
	// orderamountDescOrderID is the schema descriptor for order_id field.
	orderamountDescOrderID := orderamountFields[0].Descriptor()
	// orderamount.OrderIDValidator is a validator for the "order_id" field. It is called by the builders before save.
	orderamount.OrderIDValidator = orderamountDescOrderID.Validators[0].(func(int64) error)
	orderitemMixin := schema.OrderItem{}.Mixin()
	orderitemMixinFields0 := orderitemMixin[0].Fields()
	_ = orderitemMixinFields0
	orderitemFields := schema.OrderItem{}.Fields()
	_ = orderitemFields
	// orderitemDescCreatedAt is the schema descriptor for created_at field.
	orderitemDescCreatedAt := orderitemMixinFields0[1].Descriptor()
	// orderitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderitem.DefaultCreatedAt = orderitemDescCreatedAt.Default.(func() time.Time)
	// orderitemDescUpdatedAt is the schema descriptor for updated_at field.
	orderitemDescUpdatedAt := orderitemMixinFields0[2].Descriptor()
	// orderitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderitem.DefaultUpdatedAt = orderitemDescUpdatedAt.Default.(func() time.Time)
	// orderitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderitem.UpdateDefaultUpdatedAt = orderitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderitemDescDelete is the schema descriptor for delete field.
	orderitemDescDelete := orderitemMixinFields0[3].Descriptor()
	// orderitem.DefaultDelete holds the default value on creation for the delete field.
	orderitem.DefaultDelete = orderitemDescDelete.Default.(int64)
	// orderitemDescCreatedID is the schema descriptor for created_id field.
	orderitemDescCreatedID := orderitemMixinFields0[4].Descriptor()
	// orderitem.DefaultCreatedID holds the default value on creation for the created_id field.
	orderitem.DefaultCreatedID = orderitemDescCreatedID.Default.(int64)
	// orderitemDescNumber is the schema descriptor for number field.
	orderitemDescNumber := orderitemFields[1].Descriptor()
	// orderitem.DefaultNumber holds the default value on creation for the number field.
	orderitem.DefaultNumber = orderitemDescNumber.Default.(int64)
	// orderitemDescRelatedUserProductID is the schema descriptor for related_user_product_id field.
	orderitemDescRelatedUserProductID := orderitemFields[4].Descriptor()
	// orderitem.DefaultRelatedUserProductID holds the default value on creation for the related_user_product_id field.
	orderitem.DefaultRelatedUserProductID = orderitemDescRelatedUserProductID.Default.(int64)
	orderpayMixin := schema.OrderPay{}.Mixin()
	orderpayMixinFields0 := orderpayMixin[0].Fields()
	_ = orderpayMixinFields0
	orderpayFields := schema.OrderPay{}.Fields()
	_ = orderpayFields
	// orderpayDescCreatedAt is the schema descriptor for created_at field.
	orderpayDescCreatedAt := orderpayMixinFields0[1].Descriptor()
	// orderpay.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderpay.DefaultCreatedAt = orderpayDescCreatedAt.Default.(func() time.Time)
	// orderpayDescUpdatedAt is the schema descriptor for updated_at field.
	orderpayDescUpdatedAt := orderpayMixinFields0[2].Descriptor()
	// orderpay.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderpay.DefaultUpdatedAt = orderpayDescUpdatedAt.Default.(func() time.Time)
	// orderpay.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderpay.UpdateDefaultUpdatedAt = orderpayDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderpayDescDelete is the schema descriptor for delete field.
	orderpayDescDelete := orderpayMixinFields0[3].Descriptor()
	// orderpay.DefaultDelete holds the default value on creation for the delete field.
	orderpay.DefaultDelete = orderpayDescDelete.Default.(int64)
	// orderpayDescCreatedID is the schema descriptor for created_id field.
	orderpayDescCreatedID := orderpayMixinFields0[4].Descriptor()
	// orderpay.DefaultCreatedID holds the default value on creation for the created_id field.
	orderpay.DefaultCreatedID = orderpayDescCreatedID.Default.(int64)
	ordersalesMixin := schema.OrderSales{}.Mixin()
	ordersalesMixinFields0 := ordersalesMixin[0].Fields()
	_ = ordersalesMixinFields0
	ordersalesMixinFields1 := ordersalesMixin[1].Fields()
	_ = ordersalesMixinFields1
	ordersalesFields := schema.OrderSales{}.Fields()
	_ = ordersalesFields
	// ordersalesDescCreatedAt is the schema descriptor for created_at field.
	ordersalesDescCreatedAt := ordersalesMixinFields0[1].Descriptor()
	// ordersales.DefaultCreatedAt holds the default value on creation for the created_at field.
	ordersales.DefaultCreatedAt = ordersalesDescCreatedAt.Default.(func() time.Time)
	// ordersalesDescUpdatedAt is the schema descriptor for updated_at field.
	ordersalesDescUpdatedAt := ordersalesMixinFields0[2].Descriptor()
	// ordersales.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ordersales.DefaultUpdatedAt = ordersalesDescUpdatedAt.Default.(func() time.Time)
	// ordersales.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ordersales.UpdateDefaultUpdatedAt = ordersalesDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ordersalesDescDelete is the schema descriptor for delete field.
	ordersalesDescDelete := ordersalesMixinFields0[3].Descriptor()
	// ordersales.DefaultDelete holds the default value on creation for the delete field.
	ordersales.DefaultDelete = ordersalesDescDelete.Default.(int64)
	// ordersalesDescCreatedID is the schema descriptor for created_id field.
	ordersalesDescCreatedID := ordersalesMixinFields0[4].Descriptor()
	// ordersales.DefaultCreatedID holds the default value on creation for the created_id field.
	ordersales.DefaultCreatedID = ordersalesDescCreatedID.Default.(int64)
	// ordersalesDescStatus is the schema descriptor for status field.
	ordersalesDescStatus := ordersalesMixinFields1[0].Descriptor()
	// ordersales.DefaultStatus holds the default value on creation for the status field.
	ordersales.DefaultStatus = ordersalesDescStatus.Default.(int64)
	productMixin := schema.Product{}.Mixin()
	productMixinFields0 := productMixin[0].Fields()
	_ = productMixinFields0
	productMixinFields1 := productMixin[1].Fields()
	_ = productMixinFields1
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productMixinFields0[1].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productMixinFields0[2].Descriptor()
	// product.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	product.DefaultUpdatedAt = productDescUpdatedAt.Default.(func() time.Time)
	// product.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	product.UpdateDefaultUpdatedAt = productDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productDescDelete is the schema descriptor for delete field.
	productDescDelete := productMixinFields0[3].Descriptor()
	// product.DefaultDelete holds the default value on creation for the delete field.
	product.DefaultDelete = productDescDelete.Default.(int64)
	// productDescCreatedID is the schema descriptor for created_id field.
	productDescCreatedID := productMixinFields0[4].Descriptor()
	// product.DefaultCreatedID holds the default value on creation for the created_id field.
	product.DefaultCreatedID = productDescCreatedID.Default.(int64)
	// productDescStatus is the schema descriptor for status field.
	productDescStatus := productMixinFields1[0].Descriptor()
	// product.DefaultStatus holds the default value on creation for the status field.
	product.DefaultStatus = productDescStatus.Default.(int64)
	productpropertyMixin := schema.ProductProperty{}.Mixin()
	productpropertyMixinFields0 := productpropertyMixin[0].Fields()
	_ = productpropertyMixinFields0
	productpropertyMixinFields1 := productpropertyMixin[1].Fields()
	_ = productpropertyMixinFields1
	productpropertyFields := schema.ProductProperty{}.Fields()
	_ = productpropertyFields
	// productpropertyDescCreatedAt is the schema descriptor for created_at field.
	productpropertyDescCreatedAt := productpropertyMixinFields0[1].Descriptor()
	// productproperty.DefaultCreatedAt holds the default value on creation for the created_at field.
	productproperty.DefaultCreatedAt = productpropertyDescCreatedAt.Default.(func() time.Time)
	// productpropertyDescUpdatedAt is the schema descriptor for updated_at field.
	productpropertyDescUpdatedAt := productpropertyMixinFields0[2].Descriptor()
	// productproperty.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	productproperty.DefaultUpdatedAt = productpropertyDescUpdatedAt.Default.(func() time.Time)
	// productproperty.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	productproperty.UpdateDefaultUpdatedAt = productpropertyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productpropertyDescDelete is the schema descriptor for delete field.
	productpropertyDescDelete := productpropertyMixinFields0[3].Descriptor()
	// productproperty.DefaultDelete holds the default value on creation for the delete field.
	productproperty.DefaultDelete = productpropertyDescDelete.Default.(int64)
	// productpropertyDescCreatedID is the schema descriptor for created_id field.
	productpropertyDescCreatedID := productpropertyMixinFields0[4].Descriptor()
	// productproperty.DefaultCreatedID holds the default value on creation for the created_id field.
	productproperty.DefaultCreatedID = productpropertyDescCreatedID.Default.(int64)
	// productpropertyDescStatus is the schema descriptor for status field.
	productpropertyDescStatus := productpropertyMixinFields1[0].Descriptor()
	// productproperty.DefaultStatus holds the default value on creation for the status field.
	productproperty.DefaultStatus = productpropertyDescStatus.Default.(int64)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[2].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescDelete is the schema descriptor for delete field.
	roleDescDelete := roleMixinFields0[3].Descriptor()
	// role.DefaultDelete holds the default value on creation for the delete field.
	role.DefaultDelete = roleDescDelete.Default.(int64)
	// roleDescCreatedID is the schema descriptor for created_id field.
	roleDescCreatedID := roleMixinFields0[4].Descriptor()
	// role.DefaultCreatedID holds the default value on creation for the created_id field.
	role.DefaultCreatedID = roleDescCreatedID.Default.(int64)
	// roleDescStatus is the schema descriptor for status field.
	roleDescStatus := roleMixinFields1[0].Descriptor()
	// role.DefaultStatus holds the default value on creation for the status field.
	role.DefaultStatus = roleDescStatus.Default.(int64)
	// roleDescDefaultRouter is the schema descriptor for default_router field.
	roleDescDefaultRouter := roleFields[2].Descriptor()
	// role.DefaultDefaultRouter holds the default value on creation for the default_router field.
	role.DefaultDefaultRouter = roleDescDefaultRouter.Default.(string)
	// roleDescRemark is the schema descriptor for remark field.
	roleDescRemark := roleFields[3].Descriptor()
	// role.DefaultRemark holds the default value on creation for the remark field.
	role.DefaultRemark = roleDescRemark.Default.(string)
	// roleDescOrderNo is the schema descriptor for order_no field.
	roleDescOrderNo := roleFields[4].Descriptor()
	// role.DefaultOrderNo holds the default value on creation for the order_no field.
	role.DefaultOrderNo = roleDescOrderNo.Default.(int64)
	// roleDescApis is the schema descriptor for apis field.
	roleDescApis := roleFields[5].Descriptor()
	// role.DefaultApis holds the default value on creation for the apis field.
	role.DefaultApis = roleDescApis.Default.([]int)
	scheduleMixin := schema.Schedule{}.Mixin()
	scheduleMixinFields0 := scheduleMixin[0].Fields()
	_ = scheduleMixinFields0
	scheduleMixinFields1 := scheduleMixin[1].Fields()
	_ = scheduleMixinFields1
	scheduleFields := schema.Schedule{}.Fields()
	_ = scheduleFields
	// scheduleDescCreatedAt is the schema descriptor for created_at field.
	scheduleDescCreatedAt := scheduleMixinFields0[1].Descriptor()
	// schedule.DefaultCreatedAt holds the default value on creation for the created_at field.
	schedule.DefaultCreatedAt = scheduleDescCreatedAt.Default.(func() time.Time)
	// scheduleDescUpdatedAt is the schema descriptor for updated_at field.
	scheduleDescUpdatedAt := scheduleMixinFields0[2].Descriptor()
	// schedule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	schedule.DefaultUpdatedAt = scheduleDescUpdatedAt.Default.(func() time.Time)
	// schedule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	schedule.UpdateDefaultUpdatedAt = scheduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// scheduleDescDelete is the schema descriptor for delete field.
	scheduleDescDelete := scheduleMixinFields0[3].Descriptor()
	// schedule.DefaultDelete holds the default value on creation for the delete field.
	schedule.DefaultDelete = scheduleDescDelete.Default.(int64)
	// scheduleDescCreatedID is the schema descriptor for created_id field.
	scheduleDescCreatedID := scheduleMixinFields0[4].Descriptor()
	// schedule.DefaultCreatedID holds the default value on creation for the created_id field.
	schedule.DefaultCreatedID = scheduleDescCreatedID.Default.(int64)
	// scheduleDescStatus is the schema descriptor for status field.
	scheduleDescStatus := scheduleMixinFields1[0].Descriptor()
	// schedule.DefaultStatus holds the default value on creation for the status field.
	schedule.DefaultStatus = scheduleDescStatus.Default.(int64)
	// scheduleDescPrice is the schema descriptor for price field.
	scheduleDescPrice := scheduleFields[11].Descriptor()
	// schedule.DefaultPrice holds the default value on creation for the price field.
	schedule.DefaultPrice = scheduleDescPrice.Default.(float64)
	schedulecoachMixin := schema.ScheduleCoach{}.Mixin()
	schedulecoachMixinFields0 := schedulecoachMixin[0].Fields()
	_ = schedulecoachMixinFields0
	schedulecoachMixinFields1 := schedulecoachMixin[1].Fields()
	_ = schedulecoachMixinFields1
	schedulecoachFields := schema.ScheduleCoach{}.Fields()
	_ = schedulecoachFields
	// schedulecoachDescCreatedAt is the schema descriptor for created_at field.
	schedulecoachDescCreatedAt := schedulecoachMixinFields0[1].Descriptor()
	// schedulecoach.DefaultCreatedAt holds the default value on creation for the created_at field.
	schedulecoach.DefaultCreatedAt = schedulecoachDescCreatedAt.Default.(func() time.Time)
	// schedulecoachDescUpdatedAt is the schema descriptor for updated_at field.
	schedulecoachDescUpdatedAt := schedulecoachMixinFields0[2].Descriptor()
	// schedulecoach.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	schedulecoach.DefaultUpdatedAt = schedulecoachDescUpdatedAt.Default.(func() time.Time)
	// schedulecoach.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	schedulecoach.UpdateDefaultUpdatedAt = schedulecoachDescUpdatedAt.UpdateDefault.(func() time.Time)
	// schedulecoachDescDelete is the schema descriptor for delete field.
	schedulecoachDescDelete := schedulecoachMixinFields0[3].Descriptor()
	// schedulecoach.DefaultDelete holds the default value on creation for the delete field.
	schedulecoach.DefaultDelete = schedulecoachDescDelete.Default.(int64)
	// schedulecoachDescCreatedID is the schema descriptor for created_id field.
	schedulecoachDescCreatedID := schedulecoachMixinFields0[4].Descriptor()
	// schedulecoach.DefaultCreatedID holds the default value on creation for the created_id field.
	schedulecoach.DefaultCreatedID = schedulecoachDescCreatedID.Default.(int64)
	// schedulecoachDescStatus is the schema descriptor for status field.
	schedulecoachDescStatus := schedulecoachMixinFields1[0].Descriptor()
	// schedulecoach.DefaultStatus holds the default value on creation for the status field.
	schedulecoach.DefaultStatus = schedulecoachDescStatus.Default.(int64)
	// schedulecoachDescStartAt is the schema descriptor for start_at field.
	schedulecoachDescStartAt := schedulecoachFields[5].Descriptor()
	// schedulecoach.DefaultStartAt holds the default value on creation for the start_at field.
	schedulecoach.DefaultStartAt = schedulecoachDescStartAt.Default.(func() time.Time)
	// schedulecoachDescEndAt is the schema descriptor for end_at field.
	schedulecoachDescEndAt := schedulecoachFields[6].Descriptor()
	// schedulecoach.DefaultEndAt holds the default value on creation for the end_at field.
	schedulecoach.DefaultEndAt = schedulecoachDescEndAt.Default.(func() time.Time)
	// schedulecoachDescSignStartAt is the schema descriptor for sign_start_at field.
	schedulecoachDescSignStartAt := schedulecoachFields[7].Descriptor()
	// schedulecoach.DefaultSignStartAt holds the default value on creation for the sign_start_at field.
	schedulecoach.DefaultSignStartAt = schedulecoachDescSignStartAt.Default.(func() time.Time)
	// schedulecoachDescSignEndAt is the schema descriptor for sign_end_at field.
	schedulecoachDescSignEndAt := schedulecoachFields[8].Descriptor()
	// schedulecoach.DefaultSignEndAt holds the default value on creation for the sign_end_at field.
	schedulecoach.DefaultSignEndAt = schedulecoachDescSignEndAt.Default.(func() time.Time)
	schedulememberMixin := schema.ScheduleMember{}.Mixin()
	schedulememberMixinFields0 := schedulememberMixin[0].Fields()
	_ = schedulememberMixinFields0
	schedulememberMixinFields1 := schedulememberMixin[1].Fields()
	_ = schedulememberMixinFields1
	schedulememberFields := schema.ScheduleMember{}.Fields()
	_ = schedulememberFields
	// schedulememberDescCreatedAt is the schema descriptor for created_at field.
	schedulememberDescCreatedAt := schedulememberMixinFields0[1].Descriptor()
	// schedulemember.DefaultCreatedAt holds the default value on creation for the created_at field.
	schedulemember.DefaultCreatedAt = schedulememberDescCreatedAt.Default.(func() time.Time)
	// schedulememberDescUpdatedAt is the schema descriptor for updated_at field.
	schedulememberDescUpdatedAt := schedulememberMixinFields0[2].Descriptor()
	// schedulemember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	schedulemember.DefaultUpdatedAt = schedulememberDescUpdatedAt.Default.(func() time.Time)
	// schedulemember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	schedulemember.UpdateDefaultUpdatedAt = schedulememberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// schedulememberDescDelete is the schema descriptor for delete field.
	schedulememberDescDelete := schedulememberMixinFields0[3].Descriptor()
	// schedulemember.DefaultDelete holds the default value on creation for the delete field.
	schedulemember.DefaultDelete = schedulememberDescDelete.Default.(int64)
	// schedulememberDescCreatedID is the schema descriptor for created_id field.
	schedulememberDescCreatedID := schedulememberMixinFields0[4].Descriptor()
	// schedulemember.DefaultCreatedID holds the default value on creation for the created_id field.
	schedulemember.DefaultCreatedID = schedulememberDescCreatedID.Default.(int64)
	// schedulememberDescStatus is the schema descriptor for status field.
	schedulememberDescStatus := schedulememberMixinFields1[0].Descriptor()
	// schedulemember.DefaultStatus holds the default value on creation for the status field.
	schedulemember.DefaultStatus = schedulememberDescStatus.Default.(int64)
	// schedulememberDescStartAt is the schema descriptor for start_at field.
	schedulememberDescStartAt := schedulememberFields[7].Descriptor()
	// schedulemember.DefaultStartAt holds the default value on creation for the start_at field.
	schedulemember.DefaultStartAt = schedulememberDescStartAt.Default.(func() time.Time)
	// schedulememberDescEndAt is the schema descriptor for end_at field.
	schedulememberDescEndAt := schedulememberFields[8].Descriptor()
	// schedulemember.DefaultEndAt holds the default value on creation for the end_at field.
	schedulemember.DefaultEndAt = schedulememberDescEndAt.Default.(func() time.Time)
	// schedulememberDescSignStartAt is the schema descriptor for sign_start_at field.
	schedulememberDescSignStartAt := schedulememberFields[9].Descriptor()
	// schedulemember.DefaultSignStartAt holds the default value on creation for the sign_start_at field.
	schedulemember.DefaultSignStartAt = schedulememberDescSignStartAt.Default.(func() time.Time)
	// schedulememberDescSignEndAt is the schema descriptor for sign_end_at field.
	schedulememberDescSignEndAt := schedulememberFields[10].Descriptor()
	// schedulemember.DefaultSignEndAt holds the default value on creation for the sign_end_at field.
	schedulemember.DefaultSignEndAt = schedulememberDescSignEndAt.Default.(func() time.Time)
	smsMixin := schema.Sms{}.Mixin()
	smsMixinFields0 := smsMixin[0].Fields()
	_ = smsMixinFields0
	smsFields := schema.Sms{}.Fields()
	_ = smsFields
	// smsDescCreatedAt is the schema descriptor for created_at field.
	smsDescCreatedAt := smsMixinFields0[1].Descriptor()
	// sms.DefaultCreatedAt holds the default value on creation for the created_at field.
	sms.DefaultCreatedAt = smsDescCreatedAt.Default.(func() time.Time)
	// smsDescUpdatedAt is the schema descriptor for updated_at field.
	smsDescUpdatedAt := smsMixinFields0[2].Descriptor()
	// sms.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sms.DefaultUpdatedAt = smsDescUpdatedAt.Default.(func() time.Time)
	// sms.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sms.UpdateDefaultUpdatedAt = smsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// smsDescDelete is the schema descriptor for delete field.
	smsDescDelete := smsMixinFields0[3].Descriptor()
	// sms.DefaultDelete holds the default value on creation for the delete field.
	sms.DefaultDelete = smsDescDelete.Default.(int64)
	// smsDescCreatedID is the schema descriptor for created_id field.
	smsDescCreatedID := smsMixinFields0[4].Descriptor()
	// sms.DefaultCreatedID holds the default value on creation for the created_id field.
	sms.DefaultCreatedID = smsDescCreatedID.Default.(int64)
	// smsDescNoticeCount is the schema descriptor for notice_count field.
	smsDescNoticeCount := smsFields[0].Descriptor()
	// sms.DefaultNoticeCount holds the default value on creation for the notice_count field.
	sms.DefaultNoticeCount = smsDescNoticeCount.Default.(int64)
	// smsDescUsedNotice is the schema descriptor for used_notice field.
	smsDescUsedNotice := smsFields[1].Descriptor()
	// sms.DefaultUsedNotice holds the default value on creation for the used_notice field.
	sms.DefaultUsedNotice = smsDescUsedNotice.Default.(int64)
	smslogMixin := schema.SmsLog{}.Mixin()
	smslogMixinFields0 := smslogMixin[0].Fields()
	_ = smslogMixinFields0
	smslogMixinFields1 := smslogMixin[1].Fields()
	_ = smslogMixinFields1
	smslogFields := schema.SmsLog{}.Fields()
	_ = smslogFields
	// smslogDescCreatedAt is the schema descriptor for created_at field.
	smslogDescCreatedAt := smslogMixinFields0[1].Descriptor()
	// smslog.DefaultCreatedAt holds the default value on creation for the created_at field.
	smslog.DefaultCreatedAt = smslogDescCreatedAt.Default.(func() time.Time)
	// smslogDescUpdatedAt is the schema descriptor for updated_at field.
	smslogDescUpdatedAt := smslogMixinFields0[2].Descriptor()
	// smslog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	smslog.DefaultUpdatedAt = smslogDescUpdatedAt.Default.(func() time.Time)
	// smslog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	smslog.UpdateDefaultUpdatedAt = smslogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// smslogDescDelete is the schema descriptor for delete field.
	smslogDescDelete := smslogMixinFields0[3].Descriptor()
	// smslog.DefaultDelete holds the default value on creation for the delete field.
	smslog.DefaultDelete = smslogDescDelete.Default.(int64)
	// smslogDescCreatedID is the schema descriptor for created_id field.
	smslogDescCreatedID := smslogMixinFields0[4].Descriptor()
	// smslog.DefaultCreatedID holds the default value on creation for the created_id field.
	smslog.DefaultCreatedID = smslogDescCreatedID.Default.(int64)
	// smslogDescStatus is the schema descriptor for status field.
	smslogDescStatus := smslogMixinFields1[0].Descriptor()
	// smslog.DefaultStatus holds the default value on creation for the status field.
	smslog.DefaultStatus = smslogDescStatus.Default.(int64)
	tokenMixin := schema.Token{}.Mixin()
	tokenMixinFields0 := tokenMixin[0].Fields()
	_ = tokenMixinFields0
	tokenFields := schema.Token{}.Fields()
	_ = tokenFields
	// tokenDescCreatedAt is the schema descriptor for created_at field.
	tokenDescCreatedAt := tokenMixinFields0[1].Descriptor()
	// token.DefaultCreatedAt holds the default value on creation for the created_at field.
	token.DefaultCreatedAt = tokenDescCreatedAt.Default.(func() time.Time)
	// tokenDescUpdatedAt is the schema descriptor for updated_at field.
	tokenDescUpdatedAt := tokenMixinFields0[2].Descriptor()
	// token.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	token.DefaultUpdatedAt = tokenDescUpdatedAt.Default.(func() time.Time)
	// token.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	token.UpdateDefaultUpdatedAt = tokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tokenDescDelete is the schema descriptor for delete field.
	tokenDescDelete := tokenMixinFields0[3].Descriptor()
	// token.DefaultDelete holds the default value on creation for the delete field.
	token.DefaultDelete = tokenDescDelete.Default.(int64)
	// tokenDescCreatedID is the schema descriptor for created_id field.
	tokenDescCreatedID := tokenMixinFields0[4].Descriptor()
	// token.DefaultCreatedID holds the default value on creation for the created_id field.
	token.DefaultCreatedID = tokenDescCreatedID.Default.(int64)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescDelete is the schema descriptor for delete field.
	userDescDelete := userMixinFields0[3].Descriptor()
	// user.DefaultDelete holds the default value on creation for the delete field.
	user.DefaultDelete = userDescDelete.Default.(int64)
	// userDescCreatedID is the schema descriptor for created_id field.
	userDescCreatedID := userMixinFields0[4].Descriptor()
	// user.DefaultCreatedID holds the default value on creation for the created_id field.
	user.DefaultCreatedID = userDescCreatedID.Default.(int64)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userMixinFields1[0].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int64)
	// userDescGender is the schema descriptor for gender field.
	userDescGender := userFields[2].Descriptor()
	// user.DefaultGender holds the default value on creation for the gender field.
	user.DefaultGender = userDescGender.Default.(int64)
	// userDescJobTime is the schema descriptor for job_time field.
	userDescJobTime := userFields[6].Descriptor()
	// user.DefaultJobTime holds the default value on creation for the job_time field.
	user.DefaultJobTime = userDescJobTime.Default.(int64)
	// userDescSideMode is the schema descriptor for side_mode field.
	userDescSideMode := userFields[8].Descriptor()
	// user.DefaultSideMode holds the default value on creation for the side_mode field.
	user.DefaultSideMode = userDescSideMode.Default.(string)
	// userDescBaseColor is the schema descriptor for base_color field.
	userDescBaseColor := userFields[9].Descriptor()
	// user.DefaultBaseColor holds the default value on creation for the base_color field.
	user.DefaultBaseColor = userDescBaseColor.Default.(string)
	// userDescActiveColor is the schema descriptor for active_color field.
	userDescActiveColor := userFields[10].Descriptor()
	// user.DefaultActiveColor holds the default value on creation for the active_color field.
	user.DefaultActiveColor = userDescActiveColor.Default.(string)
	venueMixin := schema.Venue{}.Mixin()
	venueMixinFields0 := venueMixin[0].Fields()
	_ = venueMixinFields0
	venueMixinFields1 := venueMixin[1].Fields()
	_ = venueMixinFields1
	venueFields := schema.Venue{}.Fields()
	_ = venueFields
	// venueDescCreatedAt is the schema descriptor for created_at field.
	venueDescCreatedAt := venueMixinFields0[1].Descriptor()
	// venue.DefaultCreatedAt holds the default value on creation for the created_at field.
	venue.DefaultCreatedAt = venueDescCreatedAt.Default.(func() time.Time)
	// venueDescUpdatedAt is the schema descriptor for updated_at field.
	venueDescUpdatedAt := venueMixinFields0[2].Descriptor()
	// venue.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	venue.DefaultUpdatedAt = venueDescUpdatedAt.Default.(func() time.Time)
	// venue.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	venue.UpdateDefaultUpdatedAt = venueDescUpdatedAt.UpdateDefault.(func() time.Time)
	// venueDescDelete is the schema descriptor for delete field.
	venueDescDelete := venueMixinFields0[3].Descriptor()
	// venue.DefaultDelete holds the default value on creation for the delete field.
	venue.DefaultDelete = venueDescDelete.Default.(int64)
	// venueDescCreatedID is the schema descriptor for created_id field.
	venueDescCreatedID := venueMixinFields0[4].Descriptor()
	// venue.DefaultCreatedID holds the default value on creation for the created_id field.
	venue.DefaultCreatedID = venueDescCreatedID.Default.(int64)
	// venueDescStatus is the schema descriptor for status field.
	venueDescStatus := venueMixinFields1[0].Descriptor()
	// venue.DefaultStatus holds the default value on creation for the status field.
	venue.DefaultStatus = venueDescStatus.Default.(int64)
	venueplaceMixin := schema.VenuePlace{}.Mixin()
	venueplaceMixinFields0 := venueplaceMixin[0].Fields()
	_ = venueplaceMixinFields0
	venueplaceMixinFields1 := venueplaceMixin[1].Fields()
	_ = venueplaceMixinFields1
	venueplaceFields := schema.VenuePlace{}.Fields()
	_ = venueplaceFields
	// venueplaceDescCreatedAt is the schema descriptor for created_at field.
	venueplaceDescCreatedAt := venueplaceMixinFields0[1].Descriptor()
	// venueplace.DefaultCreatedAt holds the default value on creation for the created_at field.
	venueplace.DefaultCreatedAt = venueplaceDescCreatedAt.Default.(func() time.Time)
	// venueplaceDescUpdatedAt is the schema descriptor for updated_at field.
	venueplaceDescUpdatedAt := venueplaceMixinFields0[2].Descriptor()
	// venueplace.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	venueplace.DefaultUpdatedAt = venueplaceDescUpdatedAt.Default.(func() time.Time)
	// venueplace.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	venueplace.UpdateDefaultUpdatedAt = venueplaceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// venueplaceDescDelete is the schema descriptor for delete field.
	venueplaceDescDelete := venueplaceMixinFields0[3].Descriptor()
	// venueplace.DefaultDelete holds the default value on creation for the delete field.
	venueplace.DefaultDelete = venueplaceDescDelete.Default.(int64)
	// venueplaceDescCreatedID is the schema descriptor for created_id field.
	venueplaceDescCreatedID := venueplaceMixinFields0[4].Descriptor()
	// venueplace.DefaultCreatedID holds the default value on creation for the created_id field.
	venueplace.DefaultCreatedID = venueplaceDescCreatedID.Default.(int64)
	// venueplaceDescStatus is the schema descriptor for status field.
	venueplaceDescStatus := venueplaceMixinFields1[0].Descriptor()
	// venueplace.DefaultStatus holds the default value on creation for the status field.
	venueplace.DefaultStatus = venueplaceDescStatus.Default.(int64)
	// venueplaceDescIsBooking is the schema descriptor for is_booking field.
	venueplaceDescIsBooking := venueplaceFields[5].Descriptor()
	// venueplace.DefaultIsBooking holds the default value on creation for the is_booking field.
	venueplace.DefaultIsBooking = venueplaceDescIsBooking.Default.(int64)
	// venueplaceDescSeat is the schema descriptor for seat field.
	venueplaceDescSeat := venueplaceFields[6].Descriptor()
	// venueplace.DefaultSeat holds the default value on creation for the seat field.
	venueplace.DefaultSeat = venueplaceDescSeat.Default.([][]*base.Seat)
}
