// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kcers/biz/dal/db/mysql/ent/smslog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SmsLog is the model entity for the SmsLog schema.
type SmsLog struct {
	config `json:"-"`
	// ID of the ent.
	// primary key
	ID int64 `json:"id,omitempty"`
	// created time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// last update time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// last delete  1:已删除
	Delete int64 `json:"delete,omitempty"`
	// created
	CreatedID int64 `json:"created_id,omitempty"`
	// 状态[0:禁用;1:正常]
	Status int64 `json:"status,omitempty"`
	// 手机号
	Mobile string `json:"mobile,omitempty"`
	// BizId
	BizID string `json:"biz_id,omitempty"`
	// 验证码
	Code string `json:"code,omitempty"`
	// 内容
	Content string `json:"content,omitempty"`
	// 通知类型[1会员;2员工]
	NotifyType int64 `json:"notify_type,omitempty"`
	// 短信模板
	Template     string `json:"template,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SmsLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case smslog.FieldID, smslog.FieldDelete, smslog.FieldCreatedID, smslog.FieldStatus, smslog.FieldNotifyType:
			values[i] = new(sql.NullInt64)
		case smslog.FieldMobile, smslog.FieldBizID, smslog.FieldCode, smslog.FieldContent, smslog.FieldTemplate:
			values[i] = new(sql.NullString)
		case smslog.FieldCreatedAt, smslog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SmsLog fields.
func (sl *SmsLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case smslog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sl.ID = int64(value.Int64)
		case smslog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sl.CreatedAt = value.Time
			}
		case smslog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sl.UpdatedAt = value.Time
			}
		case smslog.FieldDelete:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delete", values[i])
			} else if value.Valid {
				sl.Delete = value.Int64
			}
		case smslog.FieldCreatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_id", values[i])
			} else if value.Valid {
				sl.CreatedID = value.Int64
			}
		case smslog.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				sl.Status = value.Int64
			}
		case smslog.FieldMobile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mobile", values[i])
			} else if value.Valid {
				sl.Mobile = value.String
			}
		case smslog.FieldBizID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field biz_id", values[i])
			} else if value.Valid {
				sl.BizID = value.String
			}
		case smslog.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				sl.Code = value.String
			}
		case smslog.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				sl.Content = value.String
			}
		case smslog.FieldNotifyType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field notify_type", values[i])
			} else if value.Valid {
				sl.NotifyType = value.Int64
			}
		case smslog.FieldTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template", values[i])
			} else if value.Valid {
				sl.Template = value.String
			}
		default:
			sl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SmsLog.
// This includes values selected through modifiers, order, etc.
func (sl *SmsLog) Value(name string) (ent.Value, error) {
	return sl.selectValues.Get(name)
}

// Update returns a builder for updating this SmsLog.
// Note that you need to call SmsLog.Unwrap() before calling this method if this SmsLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (sl *SmsLog) Update() *SmsLogUpdateOne {
	return NewSmsLogClient(sl.config).UpdateOne(sl)
}

// Unwrap unwraps the SmsLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sl *SmsLog) Unwrap() *SmsLog {
	_tx, ok := sl.config.driver.(*txDriver)
	if !ok {
		panic("ent: SmsLog is not a transactional entity")
	}
	sl.config.driver = _tx.drv
	return sl
}

// String implements the fmt.Stringer.
func (sl *SmsLog) String() string {
	var builder strings.Builder
	builder.WriteString("SmsLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sl.ID))
	builder.WriteString("created_at=")
	builder.WriteString(sl.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sl.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("delete=")
	builder.WriteString(fmt.Sprintf("%v", sl.Delete))
	builder.WriteString(", ")
	builder.WriteString("created_id=")
	builder.WriteString(fmt.Sprintf("%v", sl.CreatedID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", sl.Status))
	builder.WriteString(", ")
	builder.WriteString("mobile=")
	builder.WriteString(sl.Mobile)
	builder.WriteString(", ")
	builder.WriteString("biz_id=")
	builder.WriteString(sl.BizID)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(sl.Code)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(sl.Content)
	builder.WriteString(", ")
	builder.WriteString("notify_type=")
	builder.WriteString(fmt.Sprintf("%v", sl.NotifyType))
	builder.WriteString(", ")
	builder.WriteString("template=")
	builder.WriteString(sl.Template)
	builder.WriteByte(')')
	return builder.String()
}

// SmsLogs is a parsable slice of SmsLog.
type SmsLogs []*SmsLog
