// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kcers/biz/dal/db/mysql/ent/member"
	"kcers/biz/dal/db/mysql/ent/predicate"
	"kcers/biz/dal/db/mysql/ent/venuemember"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VenueMemberQuery is the builder for querying VenueMember entities.
type VenueMemberQuery struct {
	config
	ctx        *QueryContext
	order      []venuemember.OrderOption
	inters     []Interceptor
	predicates []predicate.VenueMember
	withMember *MemberQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VenueMemberQuery builder.
func (vmq *VenueMemberQuery) Where(ps ...predicate.VenueMember) *VenueMemberQuery {
	vmq.predicates = append(vmq.predicates, ps...)
	return vmq
}

// Limit the number of records to be returned by this query.
func (vmq *VenueMemberQuery) Limit(limit int) *VenueMemberQuery {
	vmq.ctx.Limit = &limit
	return vmq
}

// Offset to start from.
func (vmq *VenueMemberQuery) Offset(offset int) *VenueMemberQuery {
	vmq.ctx.Offset = &offset
	return vmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vmq *VenueMemberQuery) Unique(unique bool) *VenueMemberQuery {
	vmq.ctx.Unique = &unique
	return vmq
}

// Order specifies how the records should be ordered.
func (vmq *VenueMemberQuery) Order(o ...venuemember.OrderOption) *VenueMemberQuery {
	vmq.order = append(vmq.order, o...)
	return vmq
}

// QueryMember chains the current query on the "member" edge.
func (vmq *VenueMemberQuery) QueryMember() *MemberQuery {
	query := (&MemberClient{config: vmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(venuemember.Table, venuemember.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, venuemember.MemberTable, venuemember.MemberColumn),
		)
		fromU = sqlgraph.SetNeighbors(vmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VenueMember entity from the query.
// Returns a *NotFoundError when no VenueMember was found.
func (vmq *VenueMemberQuery) First(ctx context.Context) (*VenueMember, error) {
	nodes, err := vmq.Limit(1).All(setContextOp(ctx, vmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{venuemember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vmq *VenueMemberQuery) FirstX(ctx context.Context) *VenueMember {
	node, err := vmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VenueMember ID from the query.
// Returns a *NotFoundError when no VenueMember ID was found.
func (vmq *VenueMemberQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = vmq.Limit(1).IDs(setContextOp(ctx, vmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{venuemember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vmq *VenueMemberQuery) FirstIDX(ctx context.Context) int64 {
	id, err := vmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VenueMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VenueMember entity is found.
// Returns a *NotFoundError when no VenueMember entities are found.
func (vmq *VenueMemberQuery) Only(ctx context.Context) (*VenueMember, error) {
	nodes, err := vmq.Limit(2).All(setContextOp(ctx, vmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{venuemember.Label}
	default:
		return nil, &NotSingularError{venuemember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vmq *VenueMemberQuery) OnlyX(ctx context.Context) *VenueMember {
	node, err := vmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VenueMember ID in the query.
// Returns a *NotSingularError when more than one VenueMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (vmq *VenueMemberQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = vmq.Limit(2).IDs(setContextOp(ctx, vmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{venuemember.Label}
	default:
		err = &NotSingularError{venuemember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vmq *VenueMemberQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := vmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VenueMembers.
func (vmq *VenueMemberQuery) All(ctx context.Context) ([]*VenueMember, error) {
	ctx = setContextOp(ctx, vmq.ctx, ent.OpQueryAll)
	if err := vmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VenueMember, *VenueMemberQuery]()
	return withInterceptors[[]*VenueMember](ctx, vmq, qr, vmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vmq *VenueMemberQuery) AllX(ctx context.Context) []*VenueMember {
	nodes, err := vmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VenueMember IDs.
func (vmq *VenueMemberQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if vmq.ctx.Unique == nil && vmq.path != nil {
		vmq.Unique(true)
	}
	ctx = setContextOp(ctx, vmq.ctx, ent.OpQueryIDs)
	if err = vmq.Select(venuemember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vmq *VenueMemberQuery) IDsX(ctx context.Context) []int64 {
	ids, err := vmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vmq *VenueMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vmq.ctx, ent.OpQueryCount)
	if err := vmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vmq, querierCount[*VenueMemberQuery](), vmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vmq *VenueMemberQuery) CountX(ctx context.Context) int {
	count, err := vmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vmq *VenueMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vmq.ctx, ent.OpQueryExist)
	switch _, err := vmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vmq *VenueMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := vmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VenueMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vmq *VenueMemberQuery) Clone() *VenueMemberQuery {
	if vmq == nil {
		return nil
	}
	return &VenueMemberQuery{
		config:     vmq.config,
		ctx:        vmq.ctx.Clone(),
		order:      append([]venuemember.OrderOption{}, vmq.order...),
		inters:     append([]Interceptor{}, vmq.inters...),
		predicates: append([]predicate.VenueMember{}, vmq.predicates...),
		withMember: vmq.withMember.Clone(),
		// clone intermediate query.
		sql:       vmq.sql.Clone(),
		path:      vmq.path,
		modifiers: append([]func(*sql.Selector){}, vmq.modifiers...),
	}
}

// WithMember tells the query-builder to eager-load the nodes that are connected to
// the "member" edge. The optional arguments are used to configure the query builder of the edge.
func (vmq *VenueMemberQuery) WithMember(opts ...func(*MemberQuery)) *VenueMemberQuery {
	query := (&MemberClient{config: vmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vmq.withMember = query
	return vmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VenueMember.Query().
//		GroupBy(venuemember.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vmq *VenueMemberQuery) GroupBy(field string, fields ...string) *VenueMemberGroupBy {
	vmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VenueMemberGroupBy{build: vmq}
	grbuild.flds = &vmq.ctx.Fields
	grbuild.label = venuemember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.VenueMember.Query().
//		Select(venuemember.FieldCreatedAt).
//		Scan(ctx, &v)
func (vmq *VenueMemberQuery) Select(fields ...string) *VenueMemberSelect {
	vmq.ctx.Fields = append(vmq.ctx.Fields, fields...)
	sbuild := &VenueMemberSelect{VenueMemberQuery: vmq}
	sbuild.label = venuemember.Label
	sbuild.flds, sbuild.scan = &vmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VenueMemberSelect configured with the given aggregations.
func (vmq *VenueMemberQuery) Aggregate(fns ...AggregateFunc) *VenueMemberSelect {
	return vmq.Select().Aggregate(fns...)
}

func (vmq *VenueMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vmq); err != nil {
				return err
			}
		}
	}
	for _, f := range vmq.ctx.Fields {
		if !venuemember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vmq.path != nil {
		prev, err := vmq.path(ctx)
		if err != nil {
			return err
		}
		vmq.sql = prev
	}
	return nil
}

func (vmq *VenueMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VenueMember, error) {
	var (
		nodes       = []*VenueMember{}
		_spec       = vmq.querySpec()
		loadedTypes = [1]bool{
			vmq.withMember != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VenueMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VenueMember{config: vmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(vmq.modifiers) > 0 {
		_spec.Modifiers = vmq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vmq.withMember; query != nil {
		if err := vmq.loadMember(ctx, query, nodes, nil,
			func(n *VenueMember, e *Member) { n.Edges.Member = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vmq *VenueMemberQuery) loadMember(ctx context.Context, query *MemberQuery, nodes []*VenueMember, init func(*VenueMember), assign func(*VenueMember, *Member)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*VenueMember)
	for i := range nodes {
		fk := nodes[i].MemberID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(member.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "member_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vmq *VenueMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vmq.querySpec()
	if len(vmq.modifiers) > 0 {
		_spec.Modifiers = vmq.modifiers
	}
	_spec.Node.Columns = vmq.ctx.Fields
	if len(vmq.ctx.Fields) > 0 {
		_spec.Unique = vmq.ctx.Unique != nil && *vmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vmq.driver, _spec)
}

func (vmq *VenueMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(venuemember.Table, venuemember.Columns, sqlgraph.NewFieldSpec(venuemember.FieldID, field.TypeInt64))
	_spec.From = vmq.sql
	if unique := vmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vmq.path != nil {
		_spec.Unique = true
	}
	if fields := vmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, venuemember.FieldID)
		for i := range fields {
			if fields[i] != venuemember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if vmq.withMember != nil {
			_spec.Node.AddColumnOnce(venuemember.FieldMemberID)
		}
	}
	if ps := vmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vmq *VenueMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vmq.driver.Dialect())
	t1 := builder.Table(venuemember.Table)
	columns := vmq.ctx.Fields
	if len(columns) == 0 {
		columns = venuemember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vmq.sql != nil {
		selector = vmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vmq.ctx.Unique != nil && *vmq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range vmq.modifiers {
		m(selector)
	}
	for _, p := range vmq.predicates {
		p(selector)
	}
	for _, p := range vmq.order {
		p(selector)
	}
	if offset := vmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (vmq *VenueMemberQuery) Modify(modifiers ...func(s *sql.Selector)) *VenueMemberSelect {
	vmq.modifiers = append(vmq.modifiers, modifiers...)
	return vmq.Select()
}

// VenueMemberGroupBy is the group-by builder for VenueMember entities.
type VenueMemberGroupBy struct {
	selector
	build *VenueMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vmgb *VenueMemberGroupBy) Aggregate(fns ...AggregateFunc) *VenueMemberGroupBy {
	vmgb.fns = append(vmgb.fns, fns...)
	return vmgb
}

// Scan applies the selector query and scans the result into the given value.
func (vmgb *VenueMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vmgb.build.ctx, ent.OpQueryGroupBy)
	if err := vmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VenueMemberQuery, *VenueMemberGroupBy](ctx, vmgb.build, vmgb, vmgb.build.inters, v)
}

func (vmgb *VenueMemberGroupBy) sqlScan(ctx context.Context, root *VenueMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vmgb.fns))
	for _, fn := range vmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vmgb.flds)+len(vmgb.fns))
		for _, f := range *vmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VenueMemberSelect is the builder for selecting fields of VenueMember entities.
type VenueMemberSelect struct {
	*VenueMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vms *VenueMemberSelect) Aggregate(fns ...AggregateFunc) *VenueMemberSelect {
	vms.fns = append(vms.fns, fns...)
	return vms
}

// Scan applies the selector query and scans the result into the given value.
func (vms *VenueMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vms.ctx, ent.OpQuerySelect)
	if err := vms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VenueMemberQuery, *VenueMemberSelect](ctx, vms.VenueMemberQuery, vms, vms.inters, v)
}

func (vms *VenueMemberSelect) sqlScan(ctx context.Context, root *VenueMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vms.fns))
	for _, fn := range vms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (vms *VenueMemberSelect) Modify(modifiers ...func(s *sql.Selector)) *VenueMemberSelect {
	vms.modifiers = append(vms.modifiers, modifiers...)
	return vms
}
