// Code generated by ent, DO NOT EDIT.

package schedulemember

import (
	"kcers/biz/dal/db/mysql/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// Delete applies equality check predicate on the "delete" field. It's identical to DeleteEQ.
func Delete(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldDelete, v))
}

// CreatedID applies equality check predicate on the "created_id" field. It's identical to CreatedIDEQ.
func CreatedID(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldCreatedID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldStatus, v))
}

// VenueID applies equality check predicate on the "venue_id" field. It's identical to VenueIDEQ.
func VenueID(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldVenueID, v))
}

// PlaceID applies equality check predicate on the "place_id" field. It's identical to PlaceIDEQ.
func PlaceID(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldPlaceID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldProductID, v))
}

// ScheduleID applies equality check predicate on the "schedule_id" field. It's identical to ScheduleIDEQ.
func ScheduleID(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldScheduleID, v))
}

// ScheduleName applies equality check predicate on the "schedule_name" field. It's identical to ScheduleNameEQ.
func ScheduleName(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldScheduleName, v))
}

// IsDeduct applies equality check predicate on the "is_deduct" field. It's identical to IsDeductEQ.
func IsDeduct(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldIsDeduct, v))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberID, v))
}

// MemberProductID applies equality check predicate on the "member_product_id" field. It's identical to MemberProductIDEQ.
func MemberProductID(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberProductID, v))
}

// MemberProductPropertyID applies equality check predicate on the "member_product_property_id" field. It's identical to MemberProductPropertyIDEQ.
func MemberProductPropertyID(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberProductPropertyID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldType, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldDate, v))
}

// StartAt applies equality check predicate on the "start_at" field. It's identical to StartAtEQ.
func StartAt(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldStartAt, v))
}

// EndAt applies equality check predicate on the "end_at" field. It's identical to EndAtEQ.
func EndAt(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldEndAt, v))
}

// SignStartAt applies equality check predicate on the "sign_start_at" field. It's identical to SignStartAtEQ.
func SignStartAt(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldSignStartAt, v))
}

// SignEndAt applies equality check predicate on the "sign_end_at" field. It's identical to SignEndAtEQ.
func SignEndAt(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldSignEndAt, v))
}

// MemberName applies equality check predicate on the "member_name" field. It's identical to MemberNameEQ.
func MemberName(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberName, v))
}

// MemberProductName applies equality check predicate on the "member_product_name" field. It's identical to MemberProductNameEQ.
func MemberProductName(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberProductName, v))
}

// MemberProductPropertyName applies equality check predicate on the "member_product_property_name" field. It's identical to MemberProductPropertyNameEQ.
func MemberProductPropertyName(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberProductPropertyName, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldUpdatedAt))
}

// DeleteEQ applies the EQ predicate on the "delete" field.
func DeleteEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldDelete, v))
}

// DeleteNEQ applies the NEQ predicate on the "delete" field.
func DeleteNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldDelete, v))
}

// DeleteIn applies the In predicate on the "delete" field.
func DeleteIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldDelete, vs...))
}

// DeleteNotIn applies the NotIn predicate on the "delete" field.
func DeleteNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldDelete, vs...))
}

// DeleteGT applies the GT predicate on the "delete" field.
func DeleteGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldDelete, v))
}

// DeleteGTE applies the GTE predicate on the "delete" field.
func DeleteGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldDelete, v))
}

// DeleteLT applies the LT predicate on the "delete" field.
func DeleteLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldDelete, v))
}

// DeleteLTE applies the LTE predicate on the "delete" field.
func DeleteLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldDelete, v))
}

// DeleteIsNil applies the IsNil predicate on the "delete" field.
func DeleteIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldDelete))
}

// DeleteNotNil applies the NotNil predicate on the "delete" field.
func DeleteNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldDelete))
}

// CreatedIDEQ applies the EQ predicate on the "created_id" field.
func CreatedIDEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedIDNEQ applies the NEQ predicate on the "created_id" field.
func CreatedIDNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldCreatedID, v))
}

// CreatedIDIn applies the In predicate on the "created_id" field.
func CreatedIDIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldCreatedID, vs...))
}

// CreatedIDNotIn applies the NotIn predicate on the "created_id" field.
func CreatedIDNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldCreatedID, vs...))
}

// CreatedIDGT applies the GT predicate on the "created_id" field.
func CreatedIDGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldCreatedID, v))
}

// CreatedIDGTE applies the GTE predicate on the "created_id" field.
func CreatedIDGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldCreatedID, v))
}

// CreatedIDLT applies the LT predicate on the "created_id" field.
func CreatedIDLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldCreatedID, v))
}

// CreatedIDLTE applies the LTE predicate on the "created_id" field.
func CreatedIDLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldCreatedID, v))
}

// CreatedIDIsNil applies the IsNil predicate on the "created_id" field.
func CreatedIDIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldCreatedID))
}

// CreatedIDNotNil applies the NotNil predicate on the "created_id" field.
func CreatedIDNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldCreatedID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldStatus))
}

// VenueIDEQ applies the EQ predicate on the "venue_id" field.
func VenueIDEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldVenueID, v))
}

// VenueIDNEQ applies the NEQ predicate on the "venue_id" field.
func VenueIDNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldVenueID, v))
}

// VenueIDIn applies the In predicate on the "venue_id" field.
func VenueIDIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldVenueID, vs...))
}

// VenueIDNotIn applies the NotIn predicate on the "venue_id" field.
func VenueIDNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldVenueID, vs...))
}

// VenueIDGT applies the GT predicate on the "venue_id" field.
func VenueIDGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldVenueID, v))
}

// VenueIDGTE applies the GTE predicate on the "venue_id" field.
func VenueIDGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldVenueID, v))
}

// VenueIDLT applies the LT predicate on the "venue_id" field.
func VenueIDLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldVenueID, v))
}

// VenueIDLTE applies the LTE predicate on the "venue_id" field.
func VenueIDLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldVenueID, v))
}

// VenueIDIsNil applies the IsNil predicate on the "venue_id" field.
func VenueIDIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldVenueID))
}

// VenueIDNotNil applies the NotNil predicate on the "venue_id" field.
func VenueIDNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldVenueID))
}

// PlaceIDEQ applies the EQ predicate on the "place_id" field.
func PlaceIDEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldPlaceID, v))
}

// PlaceIDNEQ applies the NEQ predicate on the "place_id" field.
func PlaceIDNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldPlaceID, v))
}

// PlaceIDIn applies the In predicate on the "place_id" field.
func PlaceIDIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldPlaceID, vs...))
}

// PlaceIDNotIn applies the NotIn predicate on the "place_id" field.
func PlaceIDNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldPlaceID, vs...))
}

// PlaceIDGT applies the GT predicate on the "place_id" field.
func PlaceIDGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldPlaceID, v))
}

// PlaceIDGTE applies the GTE predicate on the "place_id" field.
func PlaceIDGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldPlaceID, v))
}

// PlaceIDLT applies the LT predicate on the "place_id" field.
func PlaceIDLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldPlaceID, v))
}

// PlaceIDLTE applies the LTE predicate on the "place_id" field.
func PlaceIDLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldPlaceID, v))
}

// PlaceIDIsNil applies the IsNil predicate on the "place_id" field.
func PlaceIDIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldPlaceID))
}

// PlaceIDNotNil applies the NotNil predicate on the "place_id" field.
func PlaceIDNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldPlaceID))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldProductID, v))
}

// ProductIDIsNil applies the IsNil predicate on the "product_id" field.
func ProductIDIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldProductID))
}

// ProductIDNotNil applies the NotNil predicate on the "product_id" field.
func ProductIDNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldProductID))
}

// ScheduleIDEQ applies the EQ predicate on the "schedule_id" field.
func ScheduleIDEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldScheduleID, v))
}

// ScheduleIDNEQ applies the NEQ predicate on the "schedule_id" field.
func ScheduleIDNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldScheduleID, v))
}

// ScheduleIDIn applies the In predicate on the "schedule_id" field.
func ScheduleIDIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldScheduleID, vs...))
}

// ScheduleIDNotIn applies the NotIn predicate on the "schedule_id" field.
func ScheduleIDNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldScheduleID, vs...))
}

// ScheduleIDIsNil applies the IsNil predicate on the "schedule_id" field.
func ScheduleIDIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldScheduleID))
}

// ScheduleIDNotNil applies the NotNil predicate on the "schedule_id" field.
func ScheduleIDNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldScheduleID))
}

// ScheduleNameEQ applies the EQ predicate on the "schedule_name" field.
func ScheduleNameEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldScheduleName, v))
}

// ScheduleNameNEQ applies the NEQ predicate on the "schedule_name" field.
func ScheduleNameNEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldScheduleName, v))
}

// ScheduleNameIn applies the In predicate on the "schedule_name" field.
func ScheduleNameIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldScheduleName, vs...))
}

// ScheduleNameNotIn applies the NotIn predicate on the "schedule_name" field.
func ScheduleNameNotIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldScheduleName, vs...))
}

// ScheduleNameGT applies the GT predicate on the "schedule_name" field.
func ScheduleNameGT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldScheduleName, v))
}

// ScheduleNameGTE applies the GTE predicate on the "schedule_name" field.
func ScheduleNameGTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldScheduleName, v))
}

// ScheduleNameLT applies the LT predicate on the "schedule_name" field.
func ScheduleNameLT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldScheduleName, v))
}

// ScheduleNameLTE applies the LTE predicate on the "schedule_name" field.
func ScheduleNameLTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldScheduleName, v))
}

// ScheduleNameContains applies the Contains predicate on the "schedule_name" field.
func ScheduleNameContains(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContains(FieldScheduleName, v))
}

// ScheduleNameHasPrefix applies the HasPrefix predicate on the "schedule_name" field.
func ScheduleNameHasPrefix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasPrefix(FieldScheduleName, v))
}

// ScheduleNameHasSuffix applies the HasSuffix predicate on the "schedule_name" field.
func ScheduleNameHasSuffix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasSuffix(FieldScheduleName, v))
}

// ScheduleNameIsNil applies the IsNil predicate on the "schedule_name" field.
func ScheduleNameIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldScheduleName))
}

// ScheduleNameNotNil applies the NotNil predicate on the "schedule_name" field.
func ScheduleNameNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldScheduleName))
}

// ScheduleNameEqualFold applies the EqualFold predicate on the "schedule_name" field.
func ScheduleNameEqualFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEqualFold(FieldScheduleName, v))
}

// ScheduleNameContainsFold applies the ContainsFold predicate on the "schedule_name" field.
func ScheduleNameContainsFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContainsFold(FieldScheduleName, v))
}

// IsDeductEQ applies the EQ predicate on the "is_deduct" field.
func IsDeductEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldIsDeduct, v))
}

// IsDeductNEQ applies the NEQ predicate on the "is_deduct" field.
func IsDeductNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldIsDeduct, v))
}

// IsDeductIn applies the In predicate on the "is_deduct" field.
func IsDeductIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldIsDeduct, vs...))
}

// IsDeductNotIn applies the NotIn predicate on the "is_deduct" field.
func IsDeductNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldIsDeduct, vs...))
}

// IsDeductGT applies the GT predicate on the "is_deduct" field.
func IsDeductGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldIsDeduct, v))
}

// IsDeductGTE applies the GTE predicate on the "is_deduct" field.
func IsDeductGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldIsDeduct, v))
}

// IsDeductLT applies the LT predicate on the "is_deduct" field.
func IsDeductLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldIsDeduct, v))
}

// IsDeductLTE applies the LTE predicate on the "is_deduct" field.
func IsDeductLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldIsDeduct, v))
}

// IsDeductIsNil applies the IsNil predicate on the "is_deduct" field.
func IsDeductIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldIsDeduct))
}

// IsDeductNotNil applies the NotNil predicate on the "is_deduct" field.
func IsDeductNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldIsDeduct))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldMemberID, vs...))
}

// MemberIDGT applies the GT predicate on the "member_id" field.
func MemberIDGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldMemberID, v))
}

// MemberIDGTE applies the GTE predicate on the "member_id" field.
func MemberIDGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldMemberID, v))
}

// MemberIDLT applies the LT predicate on the "member_id" field.
func MemberIDLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldMemberID, v))
}

// MemberIDLTE applies the LTE predicate on the "member_id" field.
func MemberIDLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldMemberID, v))
}

// MemberIDIsNil applies the IsNil predicate on the "member_id" field.
func MemberIDIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldMemberID))
}

// MemberIDNotNil applies the NotNil predicate on the "member_id" field.
func MemberIDNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldMemberID))
}

// MemberProductIDEQ applies the EQ predicate on the "member_product_id" field.
func MemberProductIDEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberProductID, v))
}

// MemberProductIDNEQ applies the NEQ predicate on the "member_product_id" field.
func MemberProductIDNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldMemberProductID, v))
}

// MemberProductIDIn applies the In predicate on the "member_product_id" field.
func MemberProductIDIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldMemberProductID, vs...))
}

// MemberProductIDNotIn applies the NotIn predicate on the "member_product_id" field.
func MemberProductIDNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldMemberProductID, vs...))
}

// MemberProductIDGT applies the GT predicate on the "member_product_id" field.
func MemberProductIDGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldMemberProductID, v))
}

// MemberProductIDGTE applies the GTE predicate on the "member_product_id" field.
func MemberProductIDGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldMemberProductID, v))
}

// MemberProductIDLT applies the LT predicate on the "member_product_id" field.
func MemberProductIDLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldMemberProductID, v))
}

// MemberProductIDLTE applies the LTE predicate on the "member_product_id" field.
func MemberProductIDLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldMemberProductID, v))
}

// MemberProductIDIsNil applies the IsNil predicate on the "member_product_id" field.
func MemberProductIDIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldMemberProductID))
}

// MemberProductIDNotNil applies the NotNil predicate on the "member_product_id" field.
func MemberProductIDNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldMemberProductID))
}

// MemberProductPropertyIDEQ applies the EQ predicate on the "member_product_property_id" field.
func MemberProductPropertyIDEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberProductPropertyID, v))
}

// MemberProductPropertyIDNEQ applies the NEQ predicate on the "member_product_property_id" field.
func MemberProductPropertyIDNEQ(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldMemberProductPropertyID, v))
}

// MemberProductPropertyIDIn applies the In predicate on the "member_product_property_id" field.
func MemberProductPropertyIDIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldMemberProductPropertyID, vs...))
}

// MemberProductPropertyIDNotIn applies the NotIn predicate on the "member_product_property_id" field.
func MemberProductPropertyIDNotIn(vs ...int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldMemberProductPropertyID, vs...))
}

// MemberProductPropertyIDGT applies the GT predicate on the "member_product_property_id" field.
func MemberProductPropertyIDGT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldMemberProductPropertyID, v))
}

// MemberProductPropertyIDGTE applies the GTE predicate on the "member_product_property_id" field.
func MemberProductPropertyIDGTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldMemberProductPropertyID, v))
}

// MemberProductPropertyIDLT applies the LT predicate on the "member_product_property_id" field.
func MemberProductPropertyIDLT(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldMemberProductPropertyID, v))
}

// MemberProductPropertyIDLTE applies the LTE predicate on the "member_product_property_id" field.
func MemberProductPropertyIDLTE(v int64) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldMemberProductPropertyID, v))
}

// MemberProductPropertyIDIsNil applies the IsNil predicate on the "member_product_property_id" field.
func MemberProductPropertyIDIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldMemberProductPropertyID))
}

// MemberProductPropertyIDNotNil applies the NotNil predicate on the "member_product_property_id" field.
func MemberProductPropertyIDNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldMemberProductPropertyID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContainsFold(FieldType, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldDate, v))
}

// DateIsNil applies the IsNil predicate on the "date" field.
func DateIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldDate))
}

// DateNotNil applies the NotNil predicate on the "date" field.
func DateNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldDate))
}

// StartAtEQ applies the EQ predicate on the "start_at" field.
func StartAtEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldStartAt, v))
}

// StartAtNEQ applies the NEQ predicate on the "start_at" field.
func StartAtNEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldStartAt, v))
}

// StartAtIn applies the In predicate on the "start_at" field.
func StartAtIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldStartAt, vs...))
}

// StartAtNotIn applies the NotIn predicate on the "start_at" field.
func StartAtNotIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldStartAt, vs...))
}

// StartAtGT applies the GT predicate on the "start_at" field.
func StartAtGT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldStartAt, v))
}

// StartAtGTE applies the GTE predicate on the "start_at" field.
func StartAtGTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldStartAt, v))
}

// StartAtLT applies the LT predicate on the "start_at" field.
func StartAtLT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldStartAt, v))
}

// StartAtLTE applies the LTE predicate on the "start_at" field.
func StartAtLTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldStartAt, v))
}

// StartAtIsNil applies the IsNil predicate on the "start_at" field.
func StartAtIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldStartAt))
}

// StartAtNotNil applies the NotNil predicate on the "start_at" field.
func StartAtNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldStartAt))
}

// EndAtEQ applies the EQ predicate on the "end_at" field.
func EndAtEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldEndAt, v))
}

// EndAtNEQ applies the NEQ predicate on the "end_at" field.
func EndAtNEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldEndAt, v))
}

// EndAtIn applies the In predicate on the "end_at" field.
func EndAtIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldEndAt, vs...))
}

// EndAtNotIn applies the NotIn predicate on the "end_at" field.
func EndAtNotIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldEndAt, vs...))
}

// EndAtGT applies the GT predicate on the "end_at" field.
func EndAtGT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldEndAt, v))
}

// EndAtGTE applies the GTE predicate on the "end_at" field.
func EndAtGTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldEndAt, v))
}

// EndAtLT applies the LT predicate on the "end_at" field.
func EndAtLT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldEndAt, v))
}

// EndAtLTE applies the LTE predicate on the "end_at" field.
func EndAtLTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldEndAt, v))
}

// EndAtIsNil applies the IsNil predicate on the "end_at" field.
func EndAtIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldEndAt))
}

// EndAtNotNil applies the NotNil predicate on the "end_at" field.
func EndAtNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldEndAt))
}

// SignStartAtEQ applies the EQ predicate on the "sign_start_at" field.
func SignStartAtEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldSignStartAt, v))
}

// SignStartAtNEQ applies the NEQ predicate on the "sign_start_at" field.
func SignStartAtNEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldSignStartAt, v))
}

// SignStartAtIn applies the In predicate on the "sign_start_at" field.
func SignStartAtIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldSignStartAt, vs...))
}

// SignStartAtNotIn applies the NotIn predicate on the "sign_start_at" field.
func SignStartAtNotIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldSignStartAt, vs...))
}

// SignStartAtGT applies the GT predicate on the "sign_start_at" field.
func SignStartAtGT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldSignStartAt, v))
}

// SignStartAtGTE applies the GTE predicate on the "sign_start_at" field.
func SignStartAtGTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldSignStartAt, v))
}

// SignStartAtLT applies the LT predicate on the "sign_start_at" field.
func SignStartAtLT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldSignStartAt, v))
}

// SignStartAtLTE applies the LTE predicate on the "sign_start_at" field.
func SignStartAtLTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldSignStartAt, v))
}

// SignStartAtIsNil applies the IsNil predicate on the "sign_start_at" field.
func SignStartAtIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldSignStartAt))
}

// SignStartAtNotNil applies the NotNil predicate on the "sign_start_at" field.
func SignStartAtNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldSignStartAt))
}

// SignEndAtEQ applies the EQ predicate on the "sign_end_at" field.
func SignEndAtEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldSignEndAt, v))
}

// SignEndAtNEQ applies the NEQ predicate on the "sign_end_at" field.
func SignEndAtNEQ(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldSignEndAt, v))
}

// SignEndAtIn applies the In predicate on the "sign_end_at" field.
func SignEndAtIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldSignEndAt, vs...))
}

// SignEndAtNotIn applies the NotIn predicate on the "sign_end_at" field.
func SignEndAtNotIn(vs ...time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldSignEndAt, vs...))
}

// SignEndAtGT applies the GT predicate on the "sign_end_at" field.
func SignEndAtGT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldSignEndAt, v))
}

// SignEndAtGTE applies the GTE predicate on the "sign_end_at" field.
func SignEndAtGTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldSignEndAt, v))
}

// SignEndAtLT applies the LT predicate on the "sign_end_at" field.
func SignEndAtLT(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldSignEndAt, v))
}

// SignEndAtLTE applies the LTE predicate on the "sign_end_at" field.
func SignEndAtLTE(v time.Time) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldSignEndAt, v))
}

// SignEndAtIsNil applies the IsNil predicate on the "sign_end_at" field.
func SignEndAtIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldSignEndAt))
}

// SignEndAtNotNil applies the NotNil predicate on the "sign_end_at" field.
func SignEndAtNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldSignEndAt))
}

// SeatIsNil applies the IsNil predicate on the "seat" field.
func SeatIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldSeat))
}

// SeatNotNil applies the NotNil predicate on the "seat" field.
func SeatNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldSeat))
}

// MemberNameEQ applies the EQ predicate on the "member_name" field.
func MemberNameEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberName, v))
}

// MemberNameNEQ applies the NEQ predicate on the "member_name" field.
func MemberNameNEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldMemberName, v))
}

// MemberNameIn applies the In predicate on the "member_name" field.
func MemberNameIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldMemberName, vs...))
}

// MemberNameNotIn applies the NotIn predicate on the "member_name" field.
func MemberNameNotIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldMemberName, vs...))
}

// MemberNameGT applies the GT predicate on the "member_name" field.
func MemberNameGT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldMemberName, v))
}

// MemberNameGTE applies the GTE predicate on the "member_name" field.
func MemberNameGTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldMemberName, v))
}

// MemberNameLT applies the LT predicate on the "member_name" field.
func MemberNameLT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldMemberName, v))
}

// MemberNameLTE applies the LTE predicate on the "member_name" field.
func MemberNameLTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldMemberName, v))
}

// MemberNameContains applies the Contains predicate on the "member_name" field.
func MemberNameContains(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContains(FieldMemberName, v))
}

// MemberNameHasPrefix applies the HasPrefix predicate on the "member_name" field.
func MemberNameHasPrefix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasPrefix(FieldMemberName, v))
}

// MemberNameHasSuffix applies the HasSuffix predicate on the "member_name" field.
func MemberNameHasSuffix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasSuffix(FieldMemberName, v))
}

// MemberNameIsNil applies the IsNil predicate on the "member_name" field.
func MemberNameIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldMemberName))
}

// MemberNameNotNil applies the NotNil predicate on the "member_name" field.
func MemberNameNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldMemberName))
}

// MemberNameEqualFold applies the EqualFold predicate on the "member_name" field.
func MemberNameEqualFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEqualFold(FieldMemberName, v))
}

// MemberNameContainsFold applies the ContainsFold predicate on the "member_name" field.
func MemberNameContainsFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContainsFold(FieldMemberName, v))
}

// MemberProductNameEQ applies the EQ predicate on the "member_product_name" field.
func MemberProductNameEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberProductName, v))
}

// MemberProductNameNEQ applies the NEQ predicate on the "member_product_name" field.
func MemberProductNameNEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldMemberProductName, v))
}

// MemberProductNameIn applies the In predicate on the "member_product_name" field.
func MemberProductNameIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldMemberProductName, vs...))
}

// MemberProductNameNotIn applies the NotIn predicate on the "member_product_name" field.
func MemberProductNameNotIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldMemberProductName, vs...))
}

// MemberProductNameGT applies the GT predicate on the "member_product_name" field.
func MemberProductNameGT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldMemberProductName, v))
}

// MemberProductNameGTE applies the GTE predicate on the "member_product_name" field.
func MemberProductNameGTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldMemberProductName, v))
}

// MemberProductNameLT applies the LT predicate on the "member_product_name" field.
func MemberProductNameLT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldMemberProductName, v))
}

// MemberProductNameLTE applies the LTE predicate on the "member_product_name" field.
func MemberProductNameLTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldMemberProductName, v))
}

// MemberProductNameContains applies the Contains predicate on the "member_product_name" field.
func MemberProductNameContains(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContains(FieldMemberProductName, v))
}

// MemberProductNameHasPrefix applies the HasPrefix predicate on the "member_product_name" field.
func MemberProductNameHasPrefix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasPrefix(FieldMemberProductName, v))
}

// MemberProductNameHasSuffix applies the HasSuffix predicate on the "member_product_name" field.
func MemberProductNameHasSuffix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasSuffix(FieldMemberProductName, v))
}

// MemberProductNameIsNil applies the IsNil predicate on the "member_product_name" field.
func MemberProductNameIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldMemberProductName))
}

// MemberProductNameNotNil applies the NotNil predicate on the "member_product_name" field.
func MemberProductNameNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldMemberProductName))
}

// MemberProductNameEqualFold applies the EqualFold predicate on the "member_product_name" field.
func MemberProductNameEqualFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEqualFold(FieldMemberProductName, v))
}

// MemberProductNameContainsFold applies the ContainsFold predicate on the "member_product_name" field.
func MemberProductNameContainsFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContainsFold(FieldMemberProductName, v))
}

// MemberProductPropertyNameEQ applies the EQ predicate on the "member_product_property_name" field.
func MemberProductPropertyNameEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameNEQ applies the NEQ predicate on the "member_product_property_name" field.
func MemberProductPropertyNameNEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameIn applies the In predicate on the "member_product_property_name" field.
func MemberProductPropertyNameIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldMemberProductPropertyName, vs...))
}

// MemberProductPropertyNameNotIn applies the NotIn predicate on the "member_product_property_name" field.
func MemberProductPropertyNameNotIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldMemberProductPropertyName, vs...))
}

// MemberProductPropertyNameGT applies the GT predicate on the "member_product_property_name" field.
func MemberProductPropertyNameGT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameGTE applies the GTE predicate on the "member_product_property_name" field.
func MemberProductPropertyNameGTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameLT applies the LT predicate on the "member_product_property_name" field.
func MemberProductPropertyNameLT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameLTE applies the LTE predicate on the "member_product_property_name" field.
func MemberProductPropertyNameLTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameContains applies the Contains predicate on the "member_product_property_name" field.
func MemberProductPropertyNameContains(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContains(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameHasPrefix applies the HasPrefix predicate on the "member_product_property_name" field.
func MemberProductPropertyNameHasPrefix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasPrefix(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameHasSuffix applies the HasSuffix predicate on the "member_product_property_name" field.
func MemberProductPropertyNameHasSuffix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasSuffix(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameIsNil applies the IsNil predicate on the "member_product_property_name" field.
func MemberProductPropertyNameIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldMemberProductPropertyName))
}

// MemberProductPropertyNameNotNil applies the NotNil predicate on the "member_product_property_name" field.
func MemberProductPropertyNameNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldMemberProductPropertyName))
}

// MemberProductPropertyNameEqualFold applies the EqualFold predicate on the "member_product_property_name" field.
func MemberProductPropertyNameEqualFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEqualFold(FieldMemberProductPropertyName, v))
}

// MemberProductPropertyNameContainsFold applies the ContainsFold predicate on the "member_product_property_name" field.
func MemberProductPropertyNameContainsFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContainsFold(FieldMemberProductPropertyName, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.FieldContainsFold(FieldRemark, v))
}

// HasSchedule applies the HasEdge predicate on the "schedule" edge.
func HasSchedule() predicate.ScheduleMember {
	return predicate.ScheduleMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScheduleTable, ScheduleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScheduleWith applies the HasEdge predicate on the "schedule" edge with a given conditions (other predicates).
func HasScheduleWith(preds ...predicate.Schedule) predicate.ScheduleMember {
	return predicate.ScheduleMember(func(s *sql.Selector) {
		step := newScheduleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScheduleMember) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScheduleMember) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScheduleMember) predicate.ScheduleMember {
	return predicate.ScheduleMember(sql.NotPredicates(p))
}
